### ISSUE TITLE
Version check's

### ISSUE THREAD

**Issue by kodeine** [outlandishideas/wpackagist#101]
If a plugin has a new version on composer, how would we notify user for plugin update?

**Comment by Rarst** [comment]
Who is "user" precisely in this scenario?

**Comment by kodeine** [comment]
@Rarst 
wordpress administrator,  that an update is available.

**Comment by Rarst** [comment]
You don't (notify). Composer stacks aren't meant to be controlled from WordPress admin.

On of the points is that site state is captured in `composer.lock` and the ability to change (ruin) it from WP admin should generally be disabled (commonly with `DISALLOW_FILE_MODS`).

**Comment by kodeine** [comment]
@Rarst 
Well, some of the plugins i have developed are private (commercial use) and they are on private repo's. I want to notify the customer that the plugins they bought has an update, rather than we reaching out to them and letting them know.

**Comment by Rarst** [comment]
How does this relate to wpackagist then?

Private plugins typically implement their own notification/update logic, it's unrelated to Composer use.
