### ISSUE TITLE
400 error on composer update

### ISSUE THREAD

**Issue by tpohare** [outlandishideas/wpackagist#103]
The "http://wpackagist.org/packages.json" file could not be downloaded (HTTP/1.1 400 Bad Request)
http://wpackagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date.

As a result updating packages fails

**Comment by Rarst** [comment]
Seems fine to me at the moment, redbot concurs https://redbot.org/?uri=http://wpackagist.org/packages.json
