### ISSUE TITLE
Unable to install taxonomy-terms-order plugin.

### ISSUE THREAD

**Issue by harshadyeola** [outlandishideas/wpackagist#106]
You have outdated version for plugin taxonomy-terms-order (1.4.4).
http://wpackagist.org/search?q=taxonomy-terms-order&type=any&search=

latest version is 1.4.6.1
https://wordpress.org/plugins/taxonomy-terms-order/developers/

Please update to latest version.

Also unable to install any version of plugin from wpackagist

```
user@localhost:~/htdocs$ composer -v require wpackagist-plugin/taxonomy-terms-order:*
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package wpackagist-plugin/taxonomy-terms-order could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

```

**Comment by tamlyn** [comment]
That's not a valid version number according to [Composer's strict rules](https://getcomposer.org/doc/04-schema.md#version). It's easy to see how a version like `1.2.3.4` could be converted into `1.2.3-p4` which is a valid Composer version. However WP versions can be any string and it's hard to write a generic converter. Any help appreciated!

**Comment by harshadyeola** [comment]
@tamlyn 

Its giving same error for  version `1.4.4`. which is listed here
http://wpackagist.org/search?q=taxonomy-terms-order&type=any&search=

```
user@localhost:~/htdocs$ composer -v require wpackagist-plugin/taxonomy-terms-order:1.4.4
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package wpackagist-plugin/taxonomy-terms-order could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by tamlyn** [comment]
Ah, yes I see it's also marked as inactive in wpackagist although it
shouldn't be. This is caused by intermittent errors in scanning the WP
plugin repo. It should reactivate itself in the next few days.

**Comment by harshadyeola** [comment]
Looks like issue is fixed. Mow able to install plugin with version 1.4.6.1 :)
