### ISSUE TITLE
cannot download prettyPhoto-media plugin 

### ISSUE THREAD

**Issue by pchapla** [outlandishideas/wpackagist#114]
When I tried to download dev-trunk, I got the following error:
[Composer\Downloader\TransportException]                                                                  
  The "https://downloads.wordpress.org/plugin/prettyphoto-media.zip" file could not be downloaded (HTTP/1.  
  1 404 Not Found) 

When I tried to download version 1.1, I got the following error:
[RuntimeException]                 
  Package could not be downloaded,   
  sh: svn: command not found

**Comment by tamlyn** [comment]
Can't see that plugin on wordpress.org https://wordpress.org/plugins/prettyphoto-media
