### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by skynet** [outlandishideas/wpackagist#119]
Are there any ways to improve speed when installing packages

**Comment by tamlyn** [comment]
Try using http://test.wpackagist.org 

See #50 for more info. Please let me know if it's better/same/worse.

**Comment by tamlyn** [comment]
Did you try this? Did it make any difference?

**Comment by skynet** [comment]
Somehow. Thank you

**Comment by richardtape** [comment]
Was skimming through issues looking for something unrelated, but spotted this so thought I'd give it a try. http://test.wpackagist.org now redirects to https://wpackagist.org so I guess this can be closed.
