### ISSUE TITLE
wordpress-seo v3.0.6

### ISSUE THREAD

**Issue by grappler** [outlandishideas/wpackagist#125]
It seems like wordpress-seo v3.0.6 was not fetched in the last sync.

**Comment by jmires** [comment]
Agree - usually it's updated right away. 3.0.6 was released a couple of days ago:
https://wordpress.org/plugins/wordpress-seo/

**Comment by chrismcmacken** [comment]
Yup, still not there

**Comment by tamlyn** [comment]
This seems to be an issue with the WP SVN server. We run `svn ls --xml http://plugins.svn.wordpress.org/` to get the latest commit date of every plugin. That lets us only request version information for the plugins that have changed. However that command is returning the wrong date for this plugin:

```xml
<entry
   kind="dir">
<name>wordpress-seo</name>
<commit
   revision="1298478">
<author>omarreiss</author>
<date>2015-12-01T15:45:21.368451Z</date>
</commit>
</entry>```

Other plugins are reporting later updated dates.

I'm stumped. @rarst, do you know who might be able to help with this?

**Comment by Rarst** [comment]
The date is correct as far as I see: https://plugins.trac.wordpress.org/log/wordpress-seo

I think the issue might be that there were _two_ releases that day — 3.0.5 and 3.0.6. Are you checking the _time_ of release as well as the date? :)

**Comment by tamlyn** [comment]
Ah yes, I hadn't noticed. OK so the last commit time we have in the DB is `2015-12-01 15:45:21` which is correct. The last fetch time is `2015-12-01 16:01:36`. We're using `$wporgClient->getPlugin($package->getName(), ['versions']);` to get the versions. Is that data live or is it cached?

**Comment by Rarst** [comment]
Not sure, there might be update lag between the two. I asked in WP slack meta channel.

**Comment by Rarst** [comment]
> If it's the plugins/info response, then it's not cached, but it's also not instantaneous. The plugin rebuild takes a few minutes after the commit. After that, the API data will be correct. https://wordpress.slack.com/archives/meta/p1449589095000604

**Comment by tamlyn** [comment]
It looks like we need to introduce a small delay in our updates so that we don't try to fetch plugin info for plugins updated in the last ~30 minutes. In the meantime I've manually bumped the last commit time for this plugin so v3.0.6 will be available in a few minutes when it rebuilds.

**Comment by jmires** [comment]
thank you!

**Comment by grappler** [comment]
Closing as it is fixed.
