### ISSUE TITLE
package info out of date

### ISSUE THREAD

**Issue by ryuudo** [outlandishideas/wpackagist#131]
I contacted the package owner of "wpackagist-plugin/wp-media-category-management", who has v1.8.1 listed on wordpress.org, but that version does not show in wpackagist. He says they've tagged the same way as the previous versions they've posted, so it should be picking up in your hourly feed, but I'm not seeing this update for a week now. Why is the latest version not showing up?

**Comment by tamlyn** [comment]
See #145
