### ISSUE TITLE
Packages stuck at old versions

### ISSUE THREAD

**Issue by shawnhooper** [outlandishideas/wpackagist#134]
I'm noticing a few packages that have updates available in the WP dashboard.  Checked wpackagist and the new versions are showing in the search results, but if I run composer update, I'm still stuck at the old version.

All the plugins in my composer.json file using "*" for the version. 

Examples:

disable-emojis, stuck at 1.5, but 1.5.1 is out
powerpress, stuck at 6.2.1, but 6.3.1 is out
woocommerce, stuck at 2.4.8, but 2.5.2 is out

Ideas?

**Comment by retlehs** [comment]
is this project still maintained? 

#133 
#132 
#131 
#128 
#124 
#123 
#122

**Comment by tamlyn** [comment]
Passively.

**Comment by aaemnnosttv** [comment]
Here's another one: [`flexible-widget-title`](http://d.pr/i/1eabm)

@tamlyn Any way for us common folk to help?

**Comment by tamlyn** [comment]
See #145
