### ISSUE TITLE
Warning: TransportException on wpackagist.org

### ISSUE THREAD

**Issue by francoisfaubert** [outlandishideas/wpackagist#138]
This morning our automated CI tool started reporting failing builds because of the following error:

```
[Composer\Downloader\TransportException]
  
Your configuration does not allow connection to http://wpackagist.org. See https://getcomposer.org/doc/06-config.md#secure-http for details.
```

The issue would seem to roughly boil down to Composer forcing https urls. Should this be the correct assumption, the wpackagist.org repo can't be read because it's domain certificate seems incorrect. 

In the meantime (or if as maintainers you don't think this is a bug) one can fix this error by disabling the "secure-http" config value as mentioned by the Composer error. 

```
   {
        "config": {
            "secure-http": false
        }
   }
```

**Comment by lukedanielson** [comment]
Also coming across this error/exception.  Is there a more secure solution to this? Setting `"secure-http": false` in the config doesn't seem to be a long-term solution.

**Comment by techknowlogick** [comment]
@lukedanielson This issue is being tracked in #139

**Comment by tamlyn** [comment]
Should be fixed now.
