### ISSUE TITLE
Invalid SSL certificate

### ISSUE THREAD

**Issue by ivankruchkoff** [outlandishideas/wpackagist#139]
wpackagist.org uses an invalid security certificate. The certificate is only valid for the following names: socialmonitor.britishcouncil.net, www.socialmonitor.britishcouncil.net (Error code: ssl_error_bad_cert_domain)  Here's the error: https://www.dropbox.com/s/8nasa2tq4mfm7hp/Screenshot%202016-02-25%2019.41.40.png?dl=0

**Comment by chrisvanpatten** [comment]
I noticed this as well. Composer's security settings now require https by default, but with the bad SSL certificate the connection fails:

```
  [Composer\Downloader\TransportException]
  The "https://wpackagist.org/packages.json" file could not be downloaded: Peer certificate CN=`socialmonitor.british
  council.net' did not match expected CN=`wpackagist.org'
  Failed to enable crypto
  failed to open stream: operation failed
```

**Comment by vinkla** [comment]
+1 We should add HTTPS support.

**Comment by tamlyn** [comment]
Our server folks have been alerted. Hopefully get this sorted soon.

**Comment by timnolte** [comment]
Thanks for making this a priority!

**Comment by jsilence** [comment]
+1

**Comment by Thadone** [comment]
+1

**Comment by rocadel** [comment]
+1

**Comment by MiquelAdell** [comment]
As lot of people with this error will come this way…
Does anyone have a quick fix for that?

I'm trying to remove the https restriction on composer but not finding where.

Maybe downgrading composer? anyone knows which version would be the latest without the https requirement?

Thanks!

**Comment by jsilence** [comment]
A quick and dirty(tm) way is to disable https in the composer.json config file:
` 
...
 "config": {
			"preferred-install": "dist",
			"secure-http": "false"
  },
...
`

**Comment by timalbert** [comment]
+1

**Comment by lukedanielson** [comment]
+1

**Comment by tamlyn** [comment]
Right. SSL is up https://wpackagist.org sorry it took so long. Please reopen this if there are any more problems.

**Comment by chrisvanpatten** [comment]
Thanks for the quick action! :rocket:

**Comment by timnolte** [comment]
Excellent work! Thanks!

**Comment by brunobuddy** [comment]
Same problem today...

The "https://wpackagist.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:0D0C50A1:asn1 encoding routines:ASN1_item_verify:unknown message digest algorithm
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed
https://wpackagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date

**Comment by duanecilliers** [comment]
Same problem today for me as well...

**Comment by vinkla** [comment]
@brunobuddy @duanecilliers it is better you open a new issue since this one has already been resolved. When you comment on old closed issues the maintainers might miss what you write or forget since they can't find it in the list of open issues.

**Comment by joshua-d-hill** [comment]
If anyone else encounters this issue, please +1 the new issue created above--thanks!
