### ISSUE TITLE
Package not active

### ISSUE THREAD

**Issue by alpipego** [outlandishideas/wpackagist#140]
This package https://wordpress.org/plugins/wp-mail-smtp/ is visible on wordpress but marked as inactive on wpackagist: http://wpackagist.org/search?q=wp-mail-smtp&type=plugin.

**Comment by alpipego** [comment]
This package however is marked as active: http://wpackagist.org/search?q=codestyling-localization&type=plugin although is has been removed from wordpress https://wordpress.org/plugins/codestyling-localization/ (a couple of months ago if I am not mistaken).

**Comment by tamlyn** [comment]
See #145
