### ISSUE TITLE
simple-301-redirects is marked not active but is still on wordpress.org

### ISSUE THREAD

**Issue by davecarlson** [outlandishideas/wpackagist#144]
As titled, the 'simple-301-redirects' isn't active on wpackagist, but checking wordpress.org version 1.07 is the latest available
<img width="978" alt="screen shot 2016-03-04 at 13 33 09" src="https://cloud.githubusercontent.com/assets/299702/13528416/bb94f470-e20d-11e5-93b7-51a844a36697.png">
<img width="970" alt="screen shot 2016-03-04 at 13 33 12" src="https://cloud.githubusercontent.com/assets/299702/13528415/bb94cf36-e20d-11e5-84ea-88049d5ce9b8.png">

**Comment by sangminYoo** [comment]
I'm experiencing the same issue.

**Comment by tamlyn** [comment]
See #145
