### ISSUE TITLE
Error: failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by ivoba** [outlandishideas/wpackagist#151]
When i add "wpackagist-plugin/social": "^3.1" i get this error:

> - Installing wpackagist-plugin/social (3.1.2)
>   Downloading: 100%  
>   web/app/plugins/social//cb93a6792f092af20b3c8b912d2cf588.zip does not exist, can not write into cache
>   
>   [ErrorException]  
>   copy(web/app/plugins/social//cb93a6792f092af20b3c8b912d2cf588.zip): failed to open stream: No su  
>   ch file or directory 

Not sure if this is a bug or a misconfiguration on my side.
Maybe you can help.

**Comment by NoelLH** [comment]
Seems unlikely to be a live, global issue. Closing for now as from 2016, please reopen if a live issue.
