### ISSUE TITLE
Download url incorrect for latest version of easy-columns plugin

### ISSUE THREAD

**Issue by neutralrockets** [outlandishideas/wpackagist#153]
Latest version of easy-columns plugin (version 2.1.3) is failing to download from wpackagist using composer as the url used is:
https://downloads.wordpress.org/plugin/easy-columns.v2.1.3.zip

However in wordpress.org the actual working download url is:
https://downloads.wordpress.org/plugin/easy-columns.2.1.3.zip

As a result I am not able to update to 2.1.3 using wpackagist and composer.

**Comment by NoelLH** [comment]
Sounds like it may be a packaging error / re-publish. Closing for now as from 2016, please reopen if a live issue.
