### ISSUE TITLE
sendgrid-email-delivery-simplified not installing latest version

### ISSUE THREAD

**Issue by chadwickcole** [outlandishideas/wpackagist#154]
Hello,

I just added this plugin to my composer.json file and specified version 1.7.6 (latest) and 1.7.5 was installed. I then changed it to use the wildcard for minor releases 1.7.\* and still only got 1.7.5.

Just thought I would pass this along.

Thanks,
Chad

**Comment by NoelLH** [comment]
Please follow #350 for a live, similar issue which should hopefully be resolved soon
