### ISSUE TITLE
Ninja Forms 2.9.39 not updated

### ISSUE THREAD

**Issue by grappler** [outlandishideas/wpackagist#155]
Hello

Ninja Forms 2.9.39 did not get updated on wpackagist when it was released 22 hours ago.

**Comment by grappler** [comment]
@tamlyn Could you manually trigger and update?

**Comment by grappler** [comment]
Does not mater `2.9.40` has been released

**Comment by tamlyn** [comment]
Updates run every hour but there's a bug which sometimes misses updates. Haven't had a chance to find what causes it. Any help welcome! Possibly related to #145.
