### ISSUE TITLE
require-featured-image not updated

### ISSUE THREAD

**Issue by fgilio** [outlandishideas/wpackagist#156]
Hi!
As the tittle says, the package 'require-featured-image' is missing an update from a month ago.
- https://wpackagist.org/search?q=require-featured-image&type=any&search=
- https://wordpress.org/plugins/require-featured-image/

Is there any way to manually trigger and update on [wpackagist.org](https://wpackagist.org)?

Thanks for this awesome service!

**Comment by NoelLH** [comment]
Please see #350. When we get the latest changes rolled out, on-demand updates will be possible.
