### ISSUE TITLE
google-xml-sitemaps is not active

### ISSUE THREAD

**Issue by ertrzyiks** [outlandishideas/wpackagist#158]
wpackagist displays 

> No version available.

but plugin is published on wordpress.org: https://wordpress.org/plugins/google-sitemap-generator/

related to #145

**Comment by swissspidy** [comment]
The plugin's slug is `google-sitemap-generator`, not `google-xml-sitemaps`.

See https://wpackagist.org/search?q=google-sitemap-generator&type=any&search=. The plugin is there.

**Comment by khromov** [comment]
@swissspidy 🥇
