### ISSUE TITLE
The "plugin/login-lockdown.v1.6.1.zip" file could not be downloaded

### ISSUE THREAD

**Issue by ofauno** [outlandishideas/wpackagist#160]
![wpack_lockdown](https://cloud.githubusercontent.com/assets/1057021/15162806/8c7f7812-16ca-11e6-800e-05781f6425f9.jpg)

guess this should be the link 👍 
- https://downloads.wordpress.org/plugin/login-lockdown.1.6.1.zip
- thanks

**Comment by tamlyn** [comment]
Looks like the WP.org API is reporting the wrong versions for this plugin. In fact the [Developers tab](https://wordpress.org/plugins/login-lockdown/developers/) contains the same broken link that we're using. For now, you can work around this by specifying the `trunk` version.

**Comment by ofauno** [comment]
* thanks I just added this on the "repositories" portion

![wa_lock](https://cloud.githubusercontent.com/assets/1057021/15164198/de787350-16d2-11e6-93e4-d8948b2ef02b.jpg)
