### ISSUE TITLE
Plugin Post Types Order

### ISSUE THREAD

**Issue by AR-and** [outlandishideas/wpackagist#161]
Hello,

This plugin is not visible on wpackagist.org
 
[https://wordpress.org/plugins/post-types-order/](https://wordpress.org/plugins/post-types-order/)

Can you add it please.

Thank you

**Comment by tamlyn** [comment]
Is this the one? https://wpackagist.org/search?q=post-types-order What problem are you experiencing?

**Comment by AR-and** [comment]
Yes, thank you !

I didn't found it because I was searching with its "real" name : https://wpackagist.org/search?q=Post+Types+Order&type=any&search=

**Comment by tamlyn** [comment]
Ah yes, the search is a bit tricky. It's on our todo list...

**Comment by AR-and** [comment]
No problem, wpackagist.org is so helpful ;)
