### ISSUE TITLE
Version misreporting for amazon-web-services

### ISSUE THREAD

**Issue by matschaffer** [outlandishideas/wpackagist#165]
If I load amazon-web-services via composer it reports 0.3.6 being downloaded:

```
❯ grep -A2 amazon-web-services composer.lock
            "name": "wpackagist-plugin/amazon-web-services",
            "version": "0.3.6",
```

But the file shows 0.3.5:

```
❯ grep -i version web/app/plugins/amazon-web-services/amazon-web-services.php
Version: 0.3.5
$GLOBALS['aws_meta']['amazon-web-services']['version'] = '0.3.5';
```

May be related to https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/issues/324

**Comment by matschaffer** [comment]
Looks like clear-cache and re-install clears it so maybe a non-issue.

**Comment by Schwankenson** [comment]
+1
`composer clearcache` fixed it

**Comment by NoelLH** [comment]
Based on the other thread, looks like a missed SVN tag on the original repo side? Let me know if I've misunderstood.
