### ISSUE TITLE
RuntimeException svn: E170000 when updating package from wpackagist using composer.

### ISSUE THREAD

**Issue by andrey-larionov** [outlandishideas/wpackagist#166]
`- Installing wpackagist-plugin/preserved-html-editor-markup-plus (1.5.3)
    Downloading: Failed       
    Failed to download wpackagist-plugin/preserved-html-editor-markup-plus from dist: The "https://downloads.wordpress.org/plugin/preserved-html-editor-markup-plus.1.5.3.zip" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing wpackagist-plugin/preserved-html-editor-markup-plus (1.5.3)
    Checking out tags/1.5.3

                                                                                                                    
  [RuntimeException]                                                                                                
  Package could not be downloaded,                                                                                  
  svn: E170000: URL 'https://plugins.svn.wordpress.org/preserved-html-editor-markup-plus/tags/1.5.3' doesn't exist`

**Comment by tamlyn** [comment]
Looks like the author has mistakenly put a carriage return character into their version tag: https://plugins.svn.wordpress.org/preserved-html-editor-markup-plus/tags/1.5.3%0d/ (that `%0d` on the end is the culprit). 

If you try and download a specific version from the [WordPress plugin page](https://wordpress.org/plugins/preserved-html-editor-markup-plus/developers/) you'll see those links are also broken.
