### ISSUE TITLE
Content-Length mismatch

### ISSUE THREAD

**Issue by richardtape** [outlandishideas/wpackagist#167]
On running `composer install --prefer-dist -vvv --profile`

```
[9.3MB/0.00s] Loading composer repositories with package information
[9.6MB/1.07s] Downloading http://wpackagist.org/packages.json
[9.6MB/1.07s] Warning: Accessing wpackagist.org over http which is an insecure protocol.
[9.6MB/2.43s] Downloading http://wpackagist.org/packages.json
[9.6MB/3.81s] Downloading http://wpackagist.org/packages.json


  [Composer\Downloader\TransportException]
  Content-Length mismatch
```

At the moment, I'm using the non-ssl version because of a separate error (`OpenSSL Error messages:
  error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed`)

Some googling lead me to https://github.com/composer/composer/issues/5218 which suggests it might be to do with gzip

As that thread suggests, 

`php -i | grep mbstring.func`
mbstring.func_overload => 0 => 0 

So no overloading happening. I'm separately trying to solve the openSSL issues, but wonder if there's anything that could be done here?

**Comment by richardtape** [comment]
Additionally, I'm now at a roadblock with getting SSL working (because we're running RHEL 5, with openssl 0.9.8 which doesn't support TLS 1.1 or 1.2 it won't accept your SSL cert.) Any chance of seeing if there's a gzip reporting issue?

**Comment by richardtape** [comment]
Howdy folks, any chance of getting some extra eyes on this one? 👀

**Comment by abismail** [comment]
Yup, I'm probably going through the same process over here, imported my cecert.pem and all other solutions found for the OpenSSL issue you're having and yet the issue persists, then I allowed unsecure package installations and then I got this error. Didn't have mbstring installed in my php as per Seldaek's comment in this <a href="https://github.com/composer/composer/issues/5218">thread</a>, so I installed it, just so I could get a value ;please excuse my ignorance of whether mbstring is needed or not;
But I'm going to try and update once more now. I need this looked at as well

**Comment by khromov** [comment]
This is likely a Composer issue, please submit it here: https://github.com/composer/composer

**Comment by abismail** [comment]
damn! thank God I jumped out of PHP development! posted this over a year ago, I've since become a BI developer :smile: 

so long suckers!
