### ISSUE TITLE
Easy WP SMTP - Tags not showing

### ISSUE THREAD

**Issue by roberts91** [outlandishideas/wpackagist#170]
Hey! :)

Easy WP SMTP
https://wordpress.org/plugins/easy-wp-smtp/developers/

This plugin only shows up with dev-trunk available. Does the plugin author do anything wrong? Or is it a bug from your side? Tried to debug but could not see anything wrong on WordPress.org.

Best regards, Robert Sæther.

**Comment by tamlyn** [comment]
I see all versions listed here https://wpackagist.org/search?q=easy-wp-smtp Was that not previously the case? 

Possibly related to #173. Please reopen if it happens again.

**Comment by rfair404** [comment]
This seems to be an ongoing issue: The Easy WP SMTP plugin is on version 1.3.7 according to the .org repo, and trac for that plugin. How can we get this updated?
