### ISSUE TITLE
wpackagist.org is down

### ISSUE THREAD

**Issue by rockholla** [outlandishideas/wpackagist#171]
just in case you haven't been made aware yet.  Thanks ya'll!

**Comment by hallabro** [comment]
They have confirmed their hosting provider has network issues according to their [Twitter](https://twitter.com/wpackagist/status/744765127166164992) .

**Comment by tamlyn** [comment]
Yeah. Some kind of connectivity issue. Still haven't been told exactly what happened.

**Comment by EECOLOR** [comment]
It seems so be down again

**Comment by NoelLH** [comment]
> It seems so be down again

This was a different issue and should now be resolved @EECOLOR. Fix is rolling out depending on DNS caches.
