### ISSUE TITLE
infiniteWP client plugin

### ISSUE THREAD

**Issue by JoeriVeder** [outlandishideas/wpackagist#173]
I was looking for infiniteWP client plugin on Wpackagist and i found it, but there where no versions available. It does is available on wordpress.org (https://wordpress.org/plugins/iwp-client/) itself. Why ain't there any versions showing?

**Comment by tamlyn** [comment]
I can see all versions listed at https://wpackagist.org/search?q=iwp-client

If they were previously missing it could be related to #145
