### ISSUE TITLE
Regenerate Thumbnails Plugin 

### ISSUE THREAD

**Issue by mtruitt3215** [outlandishideas/wpackagist#174]
Hi,

Regenerate Thumbnails is missing. 

https://wordpress.org/plugins/regenerate-thumbnails/

Thank you,
Mark

**Comment by MarcGuay** [comment]
Seems to be there to me: https://wpackagist.org/search?q=regenerate-thumbnails

**Comment by mtruitt3215** [comment]
Thanks, I was trying to do it with the title vs using a dash.

Regenerate Thumbnails vs Regenerate-Thumbnails

**Comment by tamlyn** [comment]
See #100
