### ISSUE TITLE
[Bug] Wrong version is installed

### ISSUE THREAD

**Issue by stevemulligan** [outlandishideas/wpackagist#175]
When I try to install "wpackagist-plugin/robo-gallery": "2.3.1"

Instead of version 2.3.1 I get version 2.1.9.  I'm not sure if this is the right place to report this.

**Comment by kwisatz** [comment]
I can confirm I'm seeing the same behavior with other plugins. It seems to install the requested versions but the actual versions are older.
I have several plugins where I can reproduce this behavior. For instance:

```
DEBUG [9539f82f]          - Installing wpackagist-plugin/wp-members (3.1.2)
DEBUG [9539f82f]            Loading from cache
```

vs.

```
WP-Members
You have version 3.0.9.2 installed. Update to 3.1.2. View version 3.1.2 details.
```

**Comment by runofthemill** [comment]
I can also confirm the same behavior, though for me it's with external packages. 

My `composer.json` has the following section in `"repositories"` (with keys removed):

```json
	{
		"type": "package",
		"package": {
			"name": "deliciousbrains/wp-migrate-db-pro",
			"type": "wordpress-plugin",
			"version": "1.6.1",
			"dist": {
				"type": "zip",
				"url": "https://deliciousbrains.com/dl/wp-migrate-db-pro-latest.zip?licence_key=xxx&site_url=teamrubiconusa.org"
			},
			"require": {
				"composer/installers": "~1.0.12"
			}
		}
	}, {
		"type": "package",
		"package": {
			"name": "deliciousbrains/wp-migrate-db-pro-media-files",
			"type": "wordpress-plugin",
			"version": "1.4.5",
			"dist": {
				"type": "zip",
				"url": "https://deliciousbrains.com/dl/wp-migrate-db-pro-media-files-latest.zip?licence_key=xxx&site_url=teamrubiconusa.org"
			},
			"require": {
				"composer/installers": "~1.0.12"
			}
		}
	}, {
		"type": "package",
		"package": {
			"name": "deliciousbrains/wp-migrate-db-pro-cli",
			"type": "wordpress-plugin",
			"version": "1.2.5",
			"dist": {
				"type": "zip",
				"url": "https://deliciousbrains.com/dl/wp-migrate-db-pro-cli-latest.zip?licence_key=xxx&site_url=teamrubiconusa.org"
			},
			"require": {
				"composer/installers": "~1.0.12"
			}
		}
	}
```

And the `"require"` has the following:

```json
		"deliciousbrains/wp-migrate-db-pro": "^1.6.1",
		"deliciousbrains/wp-migrate-db-pro-cli": "^1.2.5",
		"deliciousbrains/wp-migrate-db-pro-media-files": "^1.4.5",
```

When it actually installs though, I'm getting v. 1.6, 1.2.4, and 1.4.4, respectively, for each plugin, which are the previous versions I had in my `composer.json`. They also loaded from cache, so perhaps it's a cache-related issue?

**Comment by kminooie** [comment]
I can also confirm that, as of the writing of this, I having this problem with following plugins: 
wpb-woocommerce-product-slider ( says 1.0.8 but installs 1.0.7 )
simple-share-buttons-adder ( says 6.2.3 but installs 6.2.2 )

I had to remove the packages from cache ( global composer directory ) and run the update again to fix the issue.

**Comment by schrapel** [comment]
Also experiencing this with `wpackagist-plugin/wp-multi-network` deleting it manually from the Composer cache fixes it

**Comment by tjend** [comment]
I have also had this problem recently for certain packages, where I need to manually clean the cache for the update to happen. The most recent was for wpackagist-plugin/cmb2 going from version 2.2.3 to 2.2.3.1.

**Comment by kwisatz** [comment]
Hey, @tamlyn is this project still being maintained? There's been no update for the last 7 months.

**Comment by rasmusbe** [comment]
Just had this problem with wpackagist-plugin/autodescription.

**Comment by khromov** [comment]
Sometimes plugin authors forget to update their plugin versions, which results in this behaviour. Since the information in this thread is out of date at this point, please make a new issue if you have this problem with a particular plugin, and make sure to check if downloading directly from WordPress.org yields the same issue first.
