### ISSUE TITLE
wpackagist-plugin/events-maker newest release not visible

### ISSUE THREAD

**Issue by joostdekeijzer** [outlandishideas/wpackagist#177]
https://wordpress.org/plugins/events-maker/ has been updated to 1.6.11 a few months ago, but wpackagist still displays 1.6.10 as the newest version.

Maybe related to #145 ?

**Comment by MarcGuay** [comment]
Same issue with https://en-ca.wordpress.org/plugins/responsive-lightbox, updated 3 months ago to 1.6.8.

**Comment by tamlyn** [comment]
See #145
