### ISSUE TITLE
Current version of rest-api not available on wpackagist

### ISSUE THREAD

**Issue by clovepod** [outlandishideas/wpackagist#180]
The current version of the rest-api plugin on wordpress.org is 2.0beta13.1:
https://wordpress.org/plugins/rest-api/changelog/

However, the most recent version available on wpackagist is 2.0beta13:
https://wpackagist.org/search?q=rest-api&type=any&search=

This point release has been out for 3 months.

**Comment by tamlyn** [comment]
Duplicate of #164
