### ISSUE TITLE
wrong plugin installed

### ISSUE THREAD

**Issue by toktor** [outlandishideas/wpackagist#181]
wpackagist shows version 3.1.7.1 as latest for mainwp-child, but from wordpress.org it does not exists. Instead if I install 3.1.7.1 (or just "*") it installs mainwp dashboard instead. When locking to 3.1.7, all is correct.

wpackagist:
https://wpackagist.org/search?q=mainwp-child&type=any&search=

mainwp-child on wordpress.org
https://wordpress.org/plugins/mainwp-child/changelog/

example composer.json:
{
  "repositories": [
    {
      "type":"composer",
      "url":"https://wpackagist.org"
    }
  ],
  "require": {
    "wpackagist-plugin/mainwp-child": "*"
  }
}

**Comment by tamlyn** [comment]
It looks like the plugin developers have messed something up. Look at the [developers tab](https://wordpress.org/plugins/mainwp-child/developers/) and you'll see 3.1.7.1 listed. If you click the svn link you'll see that they have indeed published a different plugin under that version: [3.1.7](https://plugins.svn.wordpress.org/mainwp-child/tags/3.1.7/readme.txt) vs [3.1.7.1](https://plugins.svn.wordpress.org/mainwp-child/tags/3.1.7.1/readme.txt).

**Comment by toktor** [comment]
Ah, yes, thought that might be the issue didnt know how to check for it. I'll contact the developers.
