### ISSUE TITLE
Package wpackagist-plugin/wp-piwik not found

### ISSUE THREAD

**Issue by misfist** [outlandishideas/wpackagist#182]
As noted in #145 , packages are sometime incorrectly marked as inactive.

`The requested package wpackagist-plugin/wp-piwik could not be found in any version, there may be a typo in the package name.`

The package is available on wordpress.org at: https://wordpress.org/plugins/wp-piwik/

**Comment by khromov** [comment]
WP-Piwik does currently work. Closing in favor of #185
