### ISSUE TITLE
InfiniteWP Plugin

### ISSUE THREAD

**Issue by SnakeO** [outlandishideas/wpackagist#183]
Hi, the InfiniteWP Client Plugin on Packagist is listed as inactive: https://wpackagist.org/search?q=infinitewp&type=any&search=

However, it's clearly active and was just updated 3 weeks ago: https://wordpress.org/plugins/iwp-client/

**Comment by khromov** [comment]
The InfiniteWP Client is availble under the slug `iwp-client`, you can find it here:
https://wpackagist.org/search?q=iwp-client&type=any&search=
