### ISSUE TITLE
wpackagist-plugin/custom-post-type-permalinks could not be found (solution)

### ISSUE THREAD

**Issue by pbowyer** [outlandishideas/wpackagist#185]
As noted in #182 and #145, some packages give this error

```
$ composer require wpackagist-plugin/custom-post-type-permalinks:^2.1
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package wpackagist-plugin/custom-post-type-permalinks could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, deleting ./composer.json.
```
## Investigation

Loading https://wpackagist.org/packages.json and then the sub-files, I find the entry for `wpackagist-plugin/custom-post-type-permalinks` in https://wpackagist.org/p/providers-2016-09$2494d49997a8310298fc78f488e1faf1a3fc3a0dd3daa8e07a7ebc6e479f31a3.json

This resolves to the plugin's individual file https://wpackagist.org/p/wpackagist-plugin/custom-post-type-permalinks$1cd09104e838e744b1200c1adbc9ed2ea828e456e8b5d15d04985f17a4da4849.json, which contains version details, and as far as I can tell is ok (it's valid JSON).

This pointed to the problem being with composer, and I postulated that it was caching an out-of-date wpackagist manifest.

After running `$ composer clear-cache`, the package installed.
## Differences in caching

Comparing wpackagist to Packagist

Requesting https://wpackagist.org/packages.json gives:

```
HTTP/1.1 200 OK
Server: nginx/1.8.0
Date: Thu, 29 Sep 2016 08:39:21 GMT
Content-Type: application/json
Content-Length: 1195
Last-Modified: Thu, 29 Sep 2016 08:01:16 GMT
Connection: keep-alive
ETag: "57ecca4c-4ab"
Accept-Ranges: bytes
```

By contrast requesting https://packagist.org/packages.json gives:

```
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 29 Sep 2016 08:40:04 GMT
Content-Type: application/json
Content-Length: 1193
Last-Modified: Thu, 29 Sep 2016 08:39:15 GMT
Connection: keep-alive
ETag: "57ecd333-4a9"
Cache-Control: private, max-age=0, no-cache
Accept-Ranges: bytes
```

And looking at individual files, https://wpackagist.org/p/providers-2016-09$2494d49997a8310298fc78f488e1faf1a3fc3a0dd3daa8e07a7ebc6e479f31a3.json gives:

```
HTTP/1.1 200 OK
Server: nginx/1.8.0
Date: Thu, 29 Sep 2016 08:38:25 GMT
Content-Type: application/json
Last-Modified: Thu, 29 Sep 2016 08:01:02 GMT
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
ETag: W/"57ecca3e-79ef"
Expires: Fri, 29 Sep 2017 08:38:25 GMT
Cache-Control: max-age=31536000
Content-Encoding: gzip
```

while https://packagist.org/p/provider-2016-07$3dcdf24c94e74c74054dee8f2c2c82efdcb3bc958e7bf3b3eb2889cbd641a8af.json gives:

```
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 29 Sep 2016 08:43:04 GMT
Content-Type: application/json
Content-Length: 1161651
Last-Modified: Thu, 29 Sep 2016 08:38:16 GMT
Connection: keep-alive
Vary: Accept-Encoding
ETag: "57ecd2f8-11b9b3"
Content-Encoding: gzip
```

Which could explain the difference in behaviour.

**Comment by joaquimds** [comment]
I've updated the cache header to match packagist, hopefully this fixes it.

**Comment by khromov** [comment]
We've actually added a tweak for this in our packagist mirror as well. 

Nginx config:

```
location /packages.json {
    add_header Cache-Control no-cache;
    if_modified_since off;
    add_header Last-Modified "";
    etag off;
}

location ~ ^/p/ {
    add_header Cache-Control no-cache;
    if_modified_since off;
    add_header Last-Modified "";
    etag off;
}
```
