### ISSUE TITLE
package wpackagist-plugin/types could not be found

### ISSUE THREAD

**Issue by lucien144** [outlandishideas/wpackagist#190]
The `wpackagist-plugin/types` is not active although it was working and the plugin is still on same and working URL: https://wordpress.org/plugins/types/

``` 
Problem 1
    - The requested package wpackagist-plugin/types could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by PowrSlave** [comment]
I am also having this issue. I have referenced my post, with different specifics, here: 

https://wordpress.org/support/topic/cant-install-plugin-with-wpackagist/

**Comment by tamlyn** [comment]
Thanks for reporting. Sorry about that. Seems to be working now. Probably related to #145.
