### ISSUE TITLE
Versions not available

### ISSUE THREAD

**Issue by maarten00** [outlandishideas/wpackagist#195]
Hi,

I've been using the package https://wordpress.org/plugins/radio-buttons-for-taxonomies/installation/ for a while, but suddenly all versions but dev-trunk have disappeared from wpackagist.
https://wpackagist.org/search?q=radio-buttons-for&type=any&search=

The WordPress page and the Github page (https://github.com/helgatheviking/Radio-Buttons-for-Taxonomies/issues) both have tagged versions, so no idea what is going on here..

**Comment by tamlyn** [comment]
Yeah that's weird. The other versions are listed on https://wordpress.org/plugins/radio-buttons-for-taxonomies/developers/ (which is where we get them from) and all look like valid version numbers.

**Comment by joaquimds** [comment]
This seems to be back to normal now?
