### ISSUE TITLE
pacage not available 

### ISSUE THREAD

**Issue by collonmadepvtltd** [outlandishideas/wpackagist#197]
https://wpackagist.org/search?q=metaslider&type=any&search=

https://wordpress.org/plugins/metaslider/

This plugin is listed in wpackegist.org but not listed in wordpress plugin

**Comment by runofthemill** [comment]
WPackagist.org shows "metaslider" was last fetched 2015-03-01 20:52:48, and searching wordpress.org/plugins shows there's no plugin named "metaslider", but "Meta Slider" exists (I'm assuming they're one and the same) at the URL https://wordpress.org/plugins/ml-slider/. If you [search wpackagist for ml-slider](https://wpackagist.org/search?q=ml-slider&type=any&search=), it's there :)

**Comment by tamlyn** [comment]
No longer listed on `wp.org`.
