### ISSUE TITLE
Versions not up-to-date

### ISSUE THREAD

**Issue by djanse** [outlandishideas/wpackagist#199]
I noticed that a few plugins were not fully up-to-date. Eventhough composer downloads the latest version available at wpackagist.
* [Fast Secure Contact Form](https://nl.wordpress.org/plugins/si-contact-form/) Installed 4.0.43 ([4.0.45 Available & Downloaded](https://wpackagist.org/search?q=si-contact-form))
* [WP SES](https://nl.wordpress.org/plugins/wp-ses/) Installed 0.4.8 ([0.4.9 Available & Downloaded](https://wpackagist.org/search?q=wp-ses))

**Comment by joaquimds** [comment]
This appears to now be fixed. We pushed a fix today that will hopefully prevent this happening in the future.
