### ISSUE TITLE
Visible but missing plugin(s)

### ISSUE THREAD

**Issue by clickalicious** [outlandishideas/wpackagist#200]
Hi first of all - thanks for this great piece of software and the paas!!!

While building a WP based project I've found out that some visible plugins are missing from the search on wpackagist.org:

As an example: 
 - SendinBlue for WP (URL: `https://de.wordpress.org/plugins/mailin/installation/`, Real name from URL: ´mailin`)

There are some more of those "renamed" plugins.

I assume that the plugin was first listed with it's first name `mailin` and renamed afterwards.
Maybe it's possible to find a plugin with the search on wpackagist.org with other attributes like the new name/identifiert. This would help find the dependencies.

**Comment by tamlyn** [comment]
Yeah our search is a bit rubbish and only works if you provide a substring of the "real" name: https://wpackagist.org/search?q=mailin&type=any
