### ISSUE TITLE
Custom Post Type UI not in wpackagist list

### ISSUE THREAD

**Issue by Mark-Creeten** [outlandishideas/wpackagist#201]
The plugin "Custom Post Type UI" from: https://wordpress.org/plugins/custom-post-type-ui/ is not in the wpackagist list.

**Comment by tamlyn** [comment]
This one? https://wpackagist.org/search?q=custom-post-type-ui​

**Comment by Mark-Creeten** [comment]
indeed: 
<img width="1106" alt="screen shot 2017-01-26 at 13 07 24" src="https://cloud.githubusercontent.com/assets/1265148/22330826/70e02c84-e3c8-11e6-80f0-f031f58404ac.png">

**Comment by tamlyn** [comment]
Intriguing! I can still see it. Data regenerates every hour. Maybe it's flip-flopping in and out for some bizarre reason. Will check again after three.

**Comment by tamlyn** [comment]
Yep. Gone again. Set a timer for 60 minutes and install it, quick! 

On a more serious note, I'm aware there are several bugs in WPackagist at the moment and it's very frustrating for people who rely on it. I don't have the time (or professional interest) to maintain it any more but I'm working on a plan to hand it over to someone who does.

**Comment by Mark-Creeten** [comment]
Thx for explaining, solved it by hosting it on our own composer server

**Comment by sdgluck** [comment]
Closing this as OP seems to have resolved the issue.

**Comment by leup** [comment]
To this day, this plugin is still missing from the repository. :'(
