### ISSUE TITLE
Missing package Contact form 7 to database extension

### ISSUE THREAD

**Issue by estebansanti** [outlandishideas/wpackagist#205]
composer install --no-ansi --no-dev --no-interaction --no-progress --optimize-autoloader
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package **wpackagist-plugin/contact-form-7-to-database-extension** could not be found in any version, there may be a typo in the package name.

`
"wpackagist-plugin/contact-form-7-to-database-extension": "*"
`

Same issue as described here.

https://github.com/outlandishideas/wpackagist/issues/65

**Comment by martinjobb** [comment]
So what was the solution?

**Comment by khromov** [comment]
@martinjobb The plugin has been delisted from WordPress.org and is no longer available for download:
https://wordpress.org/plugins/contact-form-7-to-database-extension/

Might be related to these security vulns: 
https://www.pluginvulnerabilities.com/tag/contact-form-7-database/

If you *really* want it, download it from the SVN:
http://plugins.svn.wordpress.org/contact-form-7-to-database-extension/
