### ISSUE TITLE
Latest version of limit-login-attempts-reloaded not available

### ISSUE THREAD

**Issue by alexanderanter** [outlandishideas/wpackagist#206]
https://wordpress.org/plugins/limit-login-attempts-reloaded/
is on version: 2.5.0 
but its on 2.4.0 on wpackagist: 
https://wpackagist.org/search?q=limit-login-attempts-reloaded

**Comment by khromov** [comment]
Consider using our WPackagist mirror which has the latest version: https://wpackagist.wpsv.se/search?q=limit-login-attempts-reloaded&type=any&search=

**Comment by joaquimds** [comment]
It looks like it's there now. Huge apologies for not getting round to your issue sooner – we handed over the maintenance of this project recently, but we screwed up the admin so no-one was being notified of new issues.

We deployed a fix today to prevent this issue happening in the future.
