### ISSUE TITLE
Relevanssi 3.5.8 update missing

### ISSUE THREAD

**Issue by cultivate** [outlandishideas/wpackagist#208]
Relevanssi has recently been updated to 3.5.8 to fix a XSS vulnerability.
It is available on wordpress.org - https://wordpress.org/plugins/relevanssi/ and appears to be on SVN https://plugins.svn.wordpress.org/relevanssi/tags/3.5.8/

**Comment by wunc** [comment]
I'm having this issue also. v3.5.8 was [released on 2017-02-16](https://www.relevanssi.com/release-notes/free-3-5-8/) (6 days ago), but wpackagist [isn't showing it](https://wpackagist.org/search?q=relevanssi&type=plugin).

**Comment by joostpasson** [comment]
+1

**Comment by mrbandfriends** [comment]
👍

**Comment by khromov** [comment]
Consider using our WPackagist mirror, which has the new version of Relevanssi: https://wpackagist.wpsv.se/search?q=relevanssi&type=any&search=

More info here: https://wpackagist.wpsv.se/

**Comment by nandastone** [comment]
+1

**Comment by wunc** [comment]
v3.5.8 is now showing.

**Comment by joaquimds** [comment]
I've identified and hopefully fixed the issue that caused this. Apologies this took so long for us to fix, the project has recently been handed over and I wasn't subscribed to any of these notifications...
