### ISSUE TITLE
The "contact-form-7-dynamic-text-extension" version 2.0.2.1 is missing

### ISSUE THREAD

**Issue by up2pk** [outlandishideas/wpackagist#209]
Version 2.0.2.1 seem to be created just a few minutes after 2.0.2 but it is not visible on wppackagist.org

The plugin has the 2.0.2.1 version, a new tag for it is also created in the repo.
https://plugins.trac.wordpress.org/changeset/1577503/contact-form-7-dynamic-text-extension

Maybe such a short time  follow up releases need some attention.
Thanks!

**Comment by khromov** [comment]
https://wpackagist.wpsv.se/search?q=ontact-form-7-dynamic-text-extension&type=any&search=

**Comment by joaquimds** [comment]
It looks like it's there now. Apologies it's taken so long for me to reply to your issue – it's very important to us that all the users of WPackagist have a good experience of it! The original maintainer of the project recently handed it over to other people at Outlandish, but we hadn't got it set up to notify us when new issues came up.

We deployed a fix today to prevent this issue happening in the future.
