### ISSUE TITLE
wpackagist.org ssl cert expired

### ISSUE THREAD

**Issue by laurentdinclaux** [outlandishideas/wpackagist#212]
The certificate expired today, so composer won't update from it anymore:

```
The "https://wpackagist.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed
https://wpackagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
```

**Comment by AnalogMemory** [comment]
This plus AWS fail, has made for a challenging day.

**Comment by maciekpaprocki** [comment]
Goddamit! it took me like 5hr and only then I realised it can be actually external issue not me messing something up :)

**Comment by Steveorevo** [comment]
Ditto. Whats the workaround to skip SSL on this?

**Comment by montemartin** [comment]
They are working on renewing the certificate. Tweeted about it just a few minutes ago - https://twitter.com/wpackagist/status/836834014405230592

**Comment by Peeeep** [comment]
Working again! Yayy

**Comment by Peeeep** [comment]
Strike my last comment please, I was mistaken :(
