### ISSUE TITLE
the pricing-deals-for-woocommerce plugin not showing versions.

### ISSUE THREAD

**Issue by Bogstag** [outlandishideas/wpackagist#213]
Only dev-trunk is available , but on [wordpress](https://wordpress.org/plugins/pricing-deals-for-woocommerce/developers/) all versions is showing.

**Comment by khromov** [comment]
Consider using our WPackagist mirror -> https://wpackagist.wpsv.se/search?q=pricing-deals-for-woocommerce&type=any&search=

**Comment by Bogstag** [comment]
Nice! Thanks! This resolves this issue for me.
