### ISSUE TITLE
Contact Form 7 Honeypot contact-form-7-honeypot

### ISSUE THREAD

**Issue by noelspringer** [outlandishideas/wpackagist#215]
Hi,

The plugin contact-form-7-honeypot seems to be missing.

Here it is on WordPress.org [Contact Form 7 Honeypot](https://wordpress.org/plugins-wp/contact-form-7-honeypot/)

Cheers,

Noel Springer

**Comment by joaquimds** [comment]
Hi – it looks to me like it's there, if you search using its slug https://wpackagist.org/search?q=contact-form-7-honeypot&type=any&search=

**Comment by noelspringer** [comment]
Thanks! My mistake.
