### ISSUE TITLE
Contact Form 7

### ISSUE THREAD

**Issue by tehmachine** [outlandishideas/wpackagist#216]
Although [Contact Form 7](https://wordpress.org/plugins/contact-form-7/) is available in the WP plugin repo it doesn't seem to show up in WPackagist.

**Comment by joaquimds** [comment]
See here – search only works by slug https://wpackagist.org/search?q=contact-form-7&type=any&search=

**Comment by akovalyov** [comment]
I've just tried the to install the plugin -- unfortunately, it didn't work as expected:

![image](https://user-images.githubusercontent.com/2339101/40486923-509b57e4-5f6b-11e8-8ee1-f7854024ed04.png)

Have I done anything wrong?
