### ISSUE TITLE
Simple Custom Post Order - version number not updating correctly

### ISSUE THREAD

**Issue by DesignyourCode** [outlandishideas/wpackagist#221]
The version for this is currently 2.3.2 and installing this via composer works. However it constantly thinks it hasn't updated and is still sitting on 2.3.1.

**Comment by khromov** [comment]
@DesignyourCode Looks like the author of the plugin has not properly tagged the release in GitHub. 

This will be resolved once @joaquimds deploys the changes in #220

**Comment by khromov** [comment]
Edited typo (GitHub -> SVN)

**Comment by joaquimds** [comment]
@khromov #220 has been deployed – see https://wpackagist.org/p/wpackagist-plugin/a-simple-backend$12c85c21aef24ca59a13bcf8a83bbfc699c217fd388d01641222ea5db4eca0d7.json for an example of your cache-buster in action.

**Comment by khromov** [comment]
@joaquimds Great!

@DesignyourCode Can you please verify if it works for you, and if you are still facing issues, please paste your `composer.lock` file in this issue. (Or at least the part that pertains to the plugin in question.)

**Comment by khromov** [comment]
The URL @joaquimds posted will stop working, but here is the content and example of the timestamp for posterity:

```
{

    "packages": {
        "wpackagist-plugin/simple-custom-post-order": {
            "2.3.2": {
                "name": "wpackagist-plugin/simple-custom-post-order",
                "version": "2.3.2",
                "version_normalized": "2.3.2.0",
                "uid": 247698,
                "dist": {
                    "type": "zip",
                    "url": "https://downloads.wordpress.org/plugin/simple-custom-post-order.zip?timestamp=1489777411"
                },
                "source": {
                    "type": "svn",
                    "url": "https://plugins.svn.wordpress.org/simple-custom-post-order/",
                    "reference": "trunk"
                },
                "homepage": "https://wordpress.org/plugins/simple-custom-post-order/",
                "require": {
                    "composer/installers": "~1.0"
                },
                "type": "wordpress-plugin"
            },
    }
}
```

**Comment by khromov** [comment]
@DesignyourCode Please ask the author to tag releases properly, otherwise you will have to specify `dev-master` as the required version in your `composer.json` file to work around this.

https://plugins.svn.wordpress.org/simple-custom-post-order/tags/

**Comment by DesignyourCode** [comment]
@khromov Apologies for the delay. I will contact the developer to indicate correct tag releases. But in the mean time use dev-master. Thank you for investigating.
