### ISSUE TITLE
WPGlobus current version missing

### ISSUE THREAD

**Issue by mockey** [outlandishideas/wpackagist#222]
There is a version 1.7.10 announced here:
https://wordpress.org/plugins/wpglobus/
Also there seems to be a tag for i on SVNt:
https://plugins.svn.wordpress.org/wpglobus/tags/1.7.10/
Any idea why it doesn't show up on wpackagist?
https://wpackagist.org/search?q=wpglobus&type=plugin

**Comment by khromov** [comment]
@mockey The author of WPGlobus did not create a tag for `1.7.10`, hence it does not show up. WordPress.org reads the `trunk` automatically in this edge case, so you can do the same by specifying `dev-master` as the required version. 

Please ask the author of the plugin to tag releases properly: 
http://plugins.svn.wordpress.org/wpglobus/tags/

**Comment by mockey** [comment]
> The author of WPGlobus did not create a tag for 1.7.10

@khromov: Thanks for looking into it.
Isn't this the tag for 1.7.10?
http://plugins.svn.wordpress.org/wpglobus/tags/1.7.10/
It seems to be at an older revision (1640560 vs. 1640561). Maybe that's the problem?

**Comment by khromov** [comment]
@mockey You are right, the tag is there.

I also checked the API, it does return the `1.7.10` tag.
https://api.wordpress.org/plugins/info/1.0/wpglobus.json?fields=versions

There does seem to be some weirdness about this particular release, because instead of pointing to the `1.7.10` zip file on WordPress.org, it links to the unversioned trunk version ( `https://downloads.wordpress.org/plugin/wpglobus.zip`) , indicating the release did not get processed correctly.

We will have to look into this further to determine the cause.

Also, I believe adding a "refresh" button to the web UI would be a way to fix issues such as these, any thoughts @joaquimds

**Comment by mockey** [comment]
> I also checked the API, it does return the 1.7.10 tag

The API is not used for updating the database? It is parsing wordpress.org instead?
https://github.com/outlandishideas/wpackagist/blob/master/src/Command/UpdateCommand.php#L31

> There does seem to be some weirdness about this particular release

As I wrote, it says: `Revision 1640560` on  http://plugins.svn.wordpress.org/wpglobus/tags/1.7.10/
while it says `Revision 1640561` for any other release. Not sure if this can be fixed be a refresh, when there is something weird in svn.
Anyway, no big deal, I'll switch to `dev-trunk` for now, thanks again.

**Comment by khromov** [comment]
@mockey The comment does not reflect the code, I think it's just a reasoning for scraping HTML vs using the API. You can see it fetches from the API here:
https://github.com/outlandishideas/wpackagist/blob/master/src/Command/UpdateCommand.php#L80

And uses the result here:
https://github.com/outlandishideas/wpackagist/blob/master/src/Command/UpdateCommand.php#L109

**Comment by mockey** [comment]
I see. It was not clear to me what `WporgClient` is. But if it uses the API it should get the `1.7.10` version also, shouldn't it?

**Comment by khromov** [comment]
@mockey Correct. But WPackagist packages are only refreshed when something new is pushed to the WPorg SVN server, so if for some reason 1.7.10 was not available after the last SVN commit it won't be updated again until the next commit. That's why I suggested a "refresh" button to force a refresh.

**Comment by mockey** [comment]
Seems to work now. Current version is 1.7.11, 1.7.10 is listed as well.
