### ISSUE TITLE
Smartling Connector missing latest version

### ISSUE THREAD

**Issue by ryanboswell** [outlandishideas/wpackagist#223]
The [Smartling Connector](https://wordpress.org/plugins/smartling-connector/) plugin released an update early last week for 1.5.1 and seem to have tagged the version correctly in SVN, but after a week it's still not appearing in WPackagist.

https://plugins.svn.wordpress.org/smartling-connector/tags/1.5.1/
https://wpackagist.org/search?q=smartling&type=plugin&search=

I noticed there's a nearly identical issue for another plugin in #222.

**Comment by khromov** [comment]
Both 1.5.1 and 1.5.2 are currently tagged correctly. This is resolved.
