### ISSUE TITLE
WordPress plugin for composer updates?

### ISSUE THREAD

**Issue by christianmagill** [outlandishideas/wpackagist#224]
I'm wondering if anyone has tackled the idea of allowing composer updates to WordPress and plugins to be triggered through the WordPress admin, or even automatically.

**Comment by sdgluck** [comment]
Hi @christianmagill! This sort of functionality isn't necessarily appropriate for wpackagist, which is a repository for WordPress plugins rather than a plugin itself. I'll leave this open for others to comment on in case they have seen or built something like what you have mentioned.

**Comment by dominiceales** [comment]
@christianmagill Have you seen Bedrock https://roots.io/bedrock/ - It manages the WP core and plugins via composer. I have used it before and find it not too bad. There are probably others too. There is no dashboard functionality, it is all composer based CLI and with a little wp-cli all is good.

**Comment by lvl99** [comment]
Maybe I'm crazy, but the Roots Bedrock usage of composer is supposed to reduce security issues by only allowing those with SSH access and permissions to manage the plugins and code which is loaded into the WP app (and also make things easier by being automated).

If you want to allow people to install/update plugins, then I would just avoid using composer and just go back to the regular WordPress method of installing/updating plugins via the WP admin.

But if you need the automation thing as well as WP admin control, then maybe it is a good idea? Seems weird and backwards to me, though.

**Comment by khromov** [comment]
@lvl99 The use case I can see for this is if you're too lazy to run `composer update` in a dev environment. But since Composer is so detached from WP:s built-in process, I have a hard time seeing it being implemented.

I'll close this issue, because I feel this is not a WPackagist bug. Perhaps there are better places to discuss this?
