### ISSUE TITLE
Using forked plugin

### ISSUE THREAD

**Issue by metadan** [outlandishideas/wpackagist#227]
I have a forked plugin that I'd like to use until a pull request is accepted but I can't seem to getting it working as advised on: https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository

I've declared a new VCS repository with a link to my fork (tried both git@ and https links) and changed the version section of the require to point at the new branch as "wpackagist-plugin/pluginName": "dev-newBranchName"

Is this a known issue/unsupported or am I doing something incorrectly?

**Comment by khromov** [comment]
@metadan It should work. Please post your `composer.json` in full so we can look for potential issues.

**Comment by khromov** [comment]
Closing due to lack of feedback. Here is a tutorial on using your own fork of a particular Composer package: https://snippets.khromov.se/composer-use-your-own-fork-for-a-package/
