### ISSUE TITLE
woocommerce-products-filter visible and active on website but not via composer

### ISSUE THREAD

**Issue by mrchimp** [outlandishideas/wpackagist#228]
I can find [this plugin](https://wordpress.org/plugins/woocommerce-products-filter/) on wpackagist.org but `composer info wpackagist-plugin/woocommerce-products-filter` gives the following error:

    [InvalidArgumentException]
      Package wpackagist-plugin/woocommerce-products-filter not found

I've tried `composer clear-cache` but it doesn't fix the error. I've also asked others to run the command and they get the same response.

**Comment by joaquimds** [comment]
This works for me:

`omposer info -a wpackagist-plugin/woocommerce-products-filter`

**Comment by mrchimp** [comment]
Well that's weird. It's working for me too now. Sorry for the noise.

**Comment by joaquimds** [comment]
No worries :-)
