### ISSUE TITLE
ssl-insecure-content-fixer has not been updated (last update in WP: 1 week ago)

### ISSUE THREAD

**Issue by GasimGasimzada** [outlandishideas/wpackagist#230]
Here is the WP Plugin URL: https://wordpress.org/plugins/ssl-insecure-content-fixer/

Current version in wpackagist: 2.3.0
Latest versoin in WP Plugin: 2.4.0

I read in other issues that some plugins get marked as inactive. Does this plugin have the same issue?

**Comment by joaquimds** [comment]
This has been updated now. Sorry for the delay.
