### ISSUE TITLE
Paid Memberships Pro current version missing

### ISSUE THREAD

**Issue by mharmuth** [outlandishideas/wpackagist#231]
Current version is 1.9.1, see: https://de.wordpress.org/plugins/paid-memberships-pro/
The tag is also in the SVN, see: https://plugins.svn.wordpress.org/paid-memberships-pro/tags/1.9.1/

Latest version in wpackagist is currently 1.9. Any ideas why the new version is missing?

**Comment by joaquimds** [comment]
This appears to be up to date now, sorry for the delay.
