### ISSUE TITLE
purple-xmls-google-product-feed-for-woocommerce

### ISSUE THREAD

**Issue by Dijkie** [outlandishideas/wpackagist#235]
Hi,

This in the composer json file:

"wpackagist-plugin/purple-xmls-google-product-feed-for-woocommerce": "3.1.7.8"

Gives me this error.

  [RuntimeException]
  Package could not be downloaded,
  sh: 1: svn: not found

Can you please help me to fix this.
Thanks

**Comment by joaquimds** [comment]
Do you have `svn` installed? If you type `svn` on the command line?

**Comment by Dijkie** [comment]
I did not...

Thank you for your reply!
