### ISSUE TITLE
Missing Easy Updates Manager

### ISSUE THREAD

**Issue by jpmelnik** [outlandishideas/wpackagist#241]
**Missing Easy Updates Manager**

[https://wordpress.org/plugins/stops-core-theme-and-plugin-updates/](url)

**Comment by joaquimds** [comment]
Search only works by https://wordpress.org slug. The slug for Easy Updates Manager is `stops-core-theme-and-plugin-updates`, and here are the search results: https://wpackagist.org/search?q=stops-core-theme-and-plugin-updates&type=any&search=

So it looks like the latest version is up. Sorry for any confusion.

**Comment by jpmelnik** [comment]
Thanks!
