### ISSUE TITLE
Did not find the  WordPress Importer plugins

### ISSUE THREAD

**Issue by va2m** [outlandishideas/wpackagist#243]
Did not find the  [WordPress Importer](https://wordpress.org/plugins/wordpress-importer/) plugins in the wpackagist.org. I have search by "WordPress Importer".

**Comment by joaquimds** [comment]
The search only works by slug: https://wpackagist.org/search?q=wordpress-importer&type=any&search=

We should allow search by name to work too, I think, or at least make it clear that the search only works by slug. @khromov, was there some issue with allowing search by name? Is it that we don't store the name, and it's hard to find out the current name of a plugin?

**Comment by va2m** [comment]
Thanks @joaquimds ! Yes, at least informe the user, like, use minus to separate words in the search field, example: "wordpress-importer" instead of "wordpress importer").
Or, if possible, convert spaces to minus on searching or something else more clear and intuitive.

**Comment by khromov** [comment]
@joaquimds The name is not currently stored, but it seems straightforward to add a column to the `packages` table and insert the plugin name as we're fetching the plugin data anyway. https://github.com/outlandishideas/wpackagist/blob/master/src/Command/UpdateCommand.php#L80

**Comment by joaquimds** [comment]
@va2m it's not as simple as that, as sometimes plugin names are completely different to the slug (this is a particularly striking example: https://en-gb.wordpress.org/plugins/stops-core-theme-and-plugin-updates/)

@khromov alright I'll sort this maybe tonight maybe tomorrow

**Comment by va2m** [comment]
@joaquimds that example was self-explanatory, I understand know. 
Before I had assumed that the slug were all similar to their names, and clearly is not. Thanks!
