### ISSUE TITLE
Missing version for ssl-insecure-content-fixer

### ISSUE THREAD

**Issue by swissspidy** [outlandishideas/wpackagist#245]
There's a version 2.4.0 on WordPress.org, it's also correctly tagged etc. Yet, it's not listed on WPackagist. I assume the tag was first missing and was added after WPackagist scanned it. There hasn't been any scan since May 14.

See https://wpackagist.org/search?q=ssl-insecure-content-fixer.

Proposed solution: Fetch plugin again.

**Comment by joaquimds** [comment]
I have refetched and 2.4 is present. Sorry for the hitch!

**Comment by swissspidy** [comment]
Thanks for resolving this so quickly!
