### ISSUE TITLE
Bad 404 page

### ISSUE THREAD

**Issue by decadence** [outlandishideas/wpackagist#248]
You have stacktrace on production site which is wrong.

For example:
https://wpackagist.org/foobar

**Comment by joaquimds** [comment]
Don't suppose you could make a PR to fix?

**Comment by decadence** [comment]
I could but I'm not familiar with Symfony which is used by you AFAIK.

**Comment by joaquimds** [comment]
Finally got around to fixing this!

**Comment by decadence** [comment]
@joaquimds are you sure?
![image](https://user-images.githubusercontent.com/1434668/31840194-ecc93344-b5ec-11e7-860a-614aad7d011d.png)

**Comment by joaquimds** [comment]
@decadence sorry i forgot to deploy it! check now?

**Comment by decadence** [comment]
Now it's fine :)
