### ISSUE TITLE
Plugin MailPoet not show versions after 3.0.0-beta.33

### ISSUE THREAD

**Issue by edgardmessias** [outlandishideas/wpackagist#249]
Plugin URL: https://wordpress.org/plugins/mailpoet/

Available tags: https://plugins.svn.wordpress.org/mailpoet/tags/

**Comment by shoetten** [comment]
Any news on this? I'd love to be able to update MailPoet through composer.

The wordpress.org API correctly returns all versions, btw:
https://api.wordpress.org/plugins/info/1.0/mailpoet.json

**Comment by joaquimds** [comment]
Sorry for the delay. I've re-fetched it. We're working on adding a front-end interface for re-fetching plugins that don't have the latest versions.

https://wpackagist.org/search?q=mailpoet

**Comment by khromov** [comment]
The versiones mentioned have been tagged, and MailPoet is now at 3.0.1, which is also tagged correctly in WPackagist. Closing.
