### ISSUE TITLE
Error 500 wpackagist page not working

### ISSUE THREAD

**Issue by hccadmin** [outlandishideas/wpackagist#250]
I've been using the awesome wpackagist (wpackagitst.org) repo heavily the past 2 weeks and it's been great! But today I cannot get the page to load. Consistenly get an internal server error. Maybe it's a DNS thing? Or web server? Anyway, wanted to let you know.

**Comment by cbravo** [comment]
+1

**Comment by joaquimds** [comment]
Sorry all, we had some downtime recently, and the monitoring was broken due to some billing issue or other such nonsense. It should be back up now.

**Comment by hccadmin** [comment]
Thank you!
