### ISSUE TITLE
better-http-redirects 1.3 is an empty package, 1.2.2 is the latest intact version on wordpress.org

### ISSUE THREAD

**Issue by modelm** [outlandishideas/wpackagist#251]
As the title says. `composer require wpackagist-plugin/better-http-redirects` results in downloading 1.3 which is an empty directory aside from .svn. `composer require wpackagist-plugin/better-http-redirects:1.2` gets the latest actual version from wordpress.org.

1.3 should be removed from wpackagist.org and 1.2.2 marked the most recent version.

**Comment by khromov** [comment]
@modelm The publishing process on WPackagist is automated, we  use the data in the WordPress.org API. You should contact the plugin author and ask them to remove this tag from SVN. Since the plugin hasn't been updated for 7 years, it's safe to say you can pin it to `1.2.*` without any major impact.
