### ISSUE TITLE
Display Widgets marked as inactive even though it's on wordpress.org

### ISSUE THREAD

**Issue by EmilEriksen** [outlandishideas/wpackagist#254]
https://wpackagist.org/search?q=display-widgets

**Comment by swissspidy** [comment]
Both https://wordpress.org/plugins/display-widgets/ and https://wordpress.org/plugins/display-widgets-seo-plus/ redirect to search, suggesting that these were (temporarily) pulled from the directory.

https://wpackagist.org/search?q=display-widgets shows `display-widgets` as active and `display-widgets-seo-plus` as inactive, while both should probably be marked as inactive.

**Comment by EmilEriksen** [comment]
@swissspidy Sorry, I forgot to close this issue. https://wordpress.org/plugins/display-widgets/ wasn't redirecting when I posted this issue but a security bug was fixed in the latest release, so it's possible it had previously been temporarily removed from the directory and WPackagist was just a little slow to update.
