### ISSUE TITLE
Plugin custom-permalinks downloads SVN structure instead of the trunk

### ISSUE THREAD

**Issue by oarmstrong** [outlandishideas/wpackagist#258]
When using `"wpackagist-plugin/custom-permalinks" : "*"` in my `composer.json`, a composer install gives me `custom-permalinks/{branches,tags,trunk}` instead of the actual plugin content in that folder. Pinning the version to `1.2.4` resolves this issue.

Is this a problem with this repo or upstream?

**Comment by JohNan** [comment]
I'm having the same issue. The entire repo is downloaded.

**Comment by djvdorp** [comment]
+1

**Comment by djvdorp** [comment]
Is this still an issue? No update here?

**Comment by djvdorp** [comment]
It seems working to me when using: `"wpackagist-plugin/custom-permalinks" : "1.2.8"`

**Comment by joaquimds** [comment]
Sorry, I don't know the cause of this issue, and it seems as though there is a simple workaround.

**Comment by khromov** [comment]
@oarmstrong Could you post the section that concerns `custom-permalinks` in your `composer.lock` file? It should be like 5-10 rows of JSON code.
