### ISSUE TITLE
Refreshing outdated plugin fails

### ISSUE THREAD

**Issue by piscis** [outlandishideas/wpackagist#260]
Hi,

I'm currently trying to update the advanced-ads plugin to 1.8.13 but only 1.8.12 is available through wpackagist. Version 1.8.13 was released 4 days ago.

Hitting the refresh button fails with a 500 Internal Server error:

How to reproduce:

Step 1:

Click on the Refresh Icon:
![screen shot 2017-11-08 at 11 11 56](https://user-images.githubusercontent.com/326163/32543357-af2b14ac-c475-11e7-9b0d-8f4ca11cd2ba.png)

Step 2:

Inspect Network traffic:
![screen shot 2017-11-08 at 11 09 49](https://user-images.githubusercontent.com/326163/32543376-bac002e6-c475-11e7-93dc-05276ecc6ade.png)

**Comment by SimeonGriggs** [comment]
Same with https://wpackagist.org/search?q=mail-logging&type=any&search=

1.8.2 was released two days ago. The plugin was removed from the directory for two days but is now restored. Perhaps this had something to do with it?

**Comment by khromov** [comment]
Closing as the latest versions are now in the WPackagist repo without any action taken.
