### ISSUE TITLE
[Feature Request] Include minimum required WordPress version in plugin composer.json

### ISSUE THREAD

**Issue by grappler** [outlandishideas/wpackagist#262]
Tablepress just increased their minimum required WordPress version to `4.9.1`.

The plugin update was not shown in the dashboard but it was downloaded ok via `composer update`.

It would be cool if wpackagist could parse the readme file and add the WordPress dependancy.

In the same pass, it would be possible to get the minimum PHP version too. https://make.wordpress.org/plugins/2017/08/29/minimum-php-version-requirement/

**Comment by khromov** [comment]
@grappler Great idea. The issue we would need to overcome is how to handle the situation where someone does not use the `johnpbloch/wordpress` package as they are either using a different package or they actually don't use Composer for WP core. 

One possible solution could be the "suggested package" syntax. https://getcomposer.org/doc/04-schema.md#suggest

**Comment by grappler** [comment]
Just got bitten by TablePress again where the minimum supported version of WordPress was increased to WP 5.3.

**Comment by szepeviktor** [comment]
me by Yoast SEO

wpackagist could provide `wpackagist/wordpress-core` and simply use Composer's constrains
