### ISSUE TITLE
WordFence 7.0.1?

### ISSUE THREAD

**Issue by andyaffleck** [outlandishideas/wpackagist#266]
7.0.1 is out and yesterday I was able to use it. Today 6.3.22 is the latest available.

**Comment by aaronhuisinga** [comment]
I'm seeing the same issue with several plugins in the last day missing the latest updates. Refreshing from the website isn't getting them, either.

**Comment by thomasfw** [comment]
+1 (Yoast SEO 6.2 also missing)

**Comment by khromov** [comment]
@joaquimds This seems specific to wpackagist.org, could you make a full refresh to fix plugins that might have gone stale?

**Comment by schliflo** [comment]
seems like it's working again now ;)
