### ISSUE TITLE
wpackagist.org plugin repository not updating

### ISSUE THREAD

**Issue by schliflo** [outlandishideas/wpackagist#267]
Building on #266 it seems like the repository is not updating for a lot of plugins. Some examples include:
https://wpackagist.org/search?q=uk-cookie-consent 2.3.7 vs 2.3.8
https://wpackagist.org/search?q=regenerate-thumbnails 3.0.1 vs 3.0.2
https://wpackagist.org/search?q=all-in-one-seo-pack 2.4.4 vs 2.4.4.1 (1 week ago)
https://wpackagist.org/search?q=wordpress-seo 6.1.1 vs 6.2 (6 days ago)

Can you please look into this? Thx! 
ping @joaquimds :)

**Comment by Beee4life** [comment]
afai understand this goes for all plugins listed. it just won't fetch any new versions.

**Comment by Beee4life** [comment]
retry it now... all new versions seem to be fetched again.

**Comment by schliflo** [comment]
@Beee4life I can confirm it's working again :)
