### ISSUE TITLE
Duplicated version with newline string [draw-attention]

### ISSUE THREAD

**Issue by mrgrain** [outlandishideas/wpackagist#271]
Hey there, I've discovered a plugin with a broken json file. Interestingly it worked until last week.
Plugin: https://wpackagist.org/search?q=draw-attention&type=any&search=

We figured it out because or packagist.com proxy failed. Here's the answer from their support team:
> So wpackagist is delivering a broken JSON file there with a duplicate entry for the version. You can try and get in touch with them to fix this. There's nothing I can do about it right now, we'll look into handling this differently but it'll be a few days before we can really fix this.

```

            "1.6.14": {
                "dist": {
                    "type": "zip",
                    "url": "https://downloads.wordpress.org/plugin/draw-attention.zip?timestamp=1523989798"
                },
                "homepage": "https://wordpress.org/plugins/draw-attention/",
                "name": "wpackagist-plugin/draw-attention",
                "require": {
                    "composer/installers": "~1.0"
                },
                "source": {
                    "reference": "trunk",
                    "type": "svn",
                    "url": "https://plugins.svn.wordpress.org/draw-attention/"
                },
                "type": "wordpress-plugin",
                "uid": 97720,
                "version": "1.6.14",
                "version_normalized": "1.6.14.0"
            },
            "1.6.14\r": {
                "dist": {
                    "type": "zip",
                    "url": "https://downloads.wordpress.org/plugin/draw-attention.1.6.14\r.zip"
                },
                "homepage": "https://wordpress.org/plugins/draw-attention/",
                "name": "wpackagist-plugin/draw-attention",
                "require": {
                    "composer/installers": "~1.0"
                },
                "source": {
                    "reference": "tags/1.6.14\r",
                    "type": "svn",
                    "url": "https://plugins.svn.wordpress.org/draw-attention/"
                },
                "type": "wordpress-plugin",
                "uid": 97740,
                "version": "1.6.14\r",
                "version_normalized": "1.6.14.0"
            },
```

> That's the JSOn they send us, as you can see there's a version "1.6.4\r" in there.

**Comment by khromov** [comment]
@mrgrain There is an issue with the tag name in the official repo. It is caused by the version `1.6.14`, which is why it worked before. I have emailed the plugins team ( plugins -at- wordpress.org ) and asked them to correct this. Once this is corrected, a plugin refresh should solve the issue.

Broken tag: 
http://plugins.svn.wordpress.org/draw-attention/tags/1.6.14%0d/
