### ISSUE TITLE
Minor annoyance: composer chokes if space before version plugin/theme

### ISSUE THREAD

**Issue by wyattbiker** [outlandishideas/wpackagist#272]
For example find a plugin and click on version.
Press Control-C or Command-C to copy to your clipboard: "wpackagist-plugin/check-email": "0.5.5"

 Then using it with composer will fail:

`composer require "wpackagist-plugin/check-email": "0.5.5"`

but this works once space is removed before version #.

`composer require "wpackagist-plugin/check-email":"0.5`.5"

**Comment by joaquimds** [comment]
sorry about this. I've just fixed it
