### ISSUE TITLE
Issue installing Remove Yoast SEO Comments plugin

### ISSUE THREAD

**Issue by valentinocossar** [outlandishideas/wpackagist#273]
Hi, the plugin [Remove Yoast SEO Comments](https://wordpress.org/plugins/remove-yoast-seo-comments/) can't be detected or activated by WordPress because the latest version installed via `composer` has the main plugin file in the subfolder `trunk`.

Can you help me?

**Comment by khromov** [comment]
Hi @valentinocossar 

The repository for that plugin is broken. I'm not even sure what the author has done but each version seems to have its own tags/trunk folder, eg:
http://plugins.svn.wordpress.org/remove-yoast-seo-comments/tags/3.1/

I'm not sure how WordPress.org recovers from his, but it's not a WPackagist issue. Please email plugins@wordpress.org with this issue and they should be able to help you fix it.
