### ISSUE TITLE
resmushit-image-optimizer Image not available on composer

### ISSUE THREAD

**Issue by gk-codi** [outlandishideas/wpackagist#276]
I am trying to installl resmushit-image-optimizer using 
```composer require wpackagist-plugin/resmushit-image-optimizer``` but I wasn't able to do that

**Comment by khromov** [comment]
What's the exact error message you are getting?

**Comment by gk-codi** [comment]
Hi khromov,

that the error that I am getting when runing `composer require  wpackagist-plugin/resmushit-image-optimizer`:
````
[InvalidArgumentException]                                                                                                                                           
  Could not find a matching version of package wpackagist-plugin/resmushit-image-optimizer. Check the package spelling, your version constraint and that the package   
  is available in a stability which matches your minimum-stability (stable).
````

**Comment by NoelLH** [comment]
@gk-codi I'm hoping this updated and is now resolved, but please reopen with info if not.
