### ISSUE TITLE
Is there a way to redirect users to packagist version instead of using wpackagist?

### ISSUE THREAD

**Issue by jtsternberg** [outlandishideas/wpackagist#278]
We actively manage the [CMB2 packagist repo](https://packagist.org/packages/webdevstudios/cmb2) and occasionally [have issues](https://wordpress.org/support/topic/older-versions-get-deleted-from-wpackagist/#post-10336872) with users who are using wppackagist. Do you provide any solution to this issue?

**Comment by jtsternberg** [comment]
Yes, we avoid pushing old tags to svn. We prefer to manage through git and packagist. I’d recommend offering some CLI output or something when plugins in the WP repo would prefer for users to use a different composer repo.

**Comment by khromov** [comment]
@jtsternberg Any reason why you don't want to push to the SVN tags? It would surely be a minor change to any automation you currently have in place.

I think you're breaking other things than just WPackagist with your current approach, as the wporg repo has no way of preserving old versions of plugins if you just commit to `trunk/`.

I'm not actually sure a repo can even send a message to the user, I thought that could only be handled on the package level via `post-install-cmd` / `post-update-cmd` commands... You are welcome to make a PR to this repo if you find a way but there's a bigger discussion to it.

**Comment by jtsternberg** [comment]
The only things breaking are the things which are relying on the svn tag structure, which we don't maintain. We maintain a git tag structure.

Saying "it would surely be a minor change" to another open-source maintainer is a bit ironic. It's a bit like saying "wpackagist honoring plugins which host their composer package with packagist would surely be a minor change".

It's certainly possible it's minor.
