### ISSUE TITLE
Plugin installed from wpackagist not recognized (GADWP)

### ISSUE THREAD

**Issue by strarsis** [outlandishideas/wpackagist#279]
A plugin installed from wpackagist (by composer), [Google Analytics Dashboard for WP](https://wordpress.org/plugins/google-analytics-dashboard-for-wp/), 
is not recognized by WordPress and not listed in plugins list. 
This occured after bumping the version number and after the composer update, 
WordPress reported the plugin as missing in plugin page.

There are indeed differences between the [zip downloadable](https://downloads.wordpress.org/plugin/google-analytics-dashboard-for-wp.zip) from 
the WordPress plugin site and what composer is pulling:
````
Only in google-analytics-dashboard-for-wp_zip: admin
Only in google-analytics-dashboard-for-wp_composer/: assets
Only in google-analytics-dashboard-for-wp_composer/: branches
Only in google-analytics-dashboard-for-wp_zip: common
Only in google-analytics-dashboard-for-wp_zip: config.php
Only in google-analytics-dashboard-for-wp_zip: front
Only in google-analytics-dashboard-for-wp_zip: gadwp.php
Only in google-analytics-dashboard-for-wp_zip: install
Only in google-analytics-dashboard-for-wp_zip: languages
Only in google-analytics-dashboard-for-wp_zip: readme.txt
Only in google-analytics-dashboard-for-wp_zip: realtime
Only in google-analytics-dashboard-for-wp_composer/: tags
Only in google-analytics-dashboard-for-wp_zip: tools
Only in google-analytics-dashboard-for-wp_composer/: trunk
````

**Comment by SimeonGriggs** [comment]
Seems to be pulling a folder containing every version of the plugin, instead of just the latest version.

**Comment by khromov** [comment]
@strarsis @SimeonGriggs This is due to an error by the author, not WPackagist. See: https://github.com/outlandishideas/wpackagist/issues/280
