### ISSUE TITLE
google-analytics-dashboard-for-wp

### ISSUE THREAD

**Issue by juslintek** [outlandishideas/wpackagist#280]
Instead of getting plugin contents it gets svn directory:
So expected results is to get this: https://plugins.svn.wordpress.org/google-analytics-dashboard-for-wp/tags/5.3.4/trunk/
But it gets this instead: https://plugins.svn.wordpress.org/google-analytics-dashboard-for-wp/tags/5.3.4/

For for this plugin i had to create this repository:
```
    {
      "type": "package",
      "package": {
        "name": "defconf/google-analytics-dashboard-for-wp",
        "version": "5.3.4",
        "type": "wordpress-plugin",
        "dist": {
          "type": "zip",
          "url": "https://downloads.wordpress.org/plugin/google-analytics-dashboard-for-wp.zip"
        },
        "source": {
          "url": "https://plugins.svn.wordpress.org/google-analytics-dashboard-for-wp/",
          "type": "svn",
          "reference": "tags/5.3.4/trunk/"

        },
        "require": {
          "composer/installers": "^1.5"
        }
      }
    },
```
And now it works, but need to manually update package version: `"defconf/google-analytics-dashboard-for-wp": "*",`

**Comment by InPhoenity** [comment]
Same issue on my side.

**Comment by khromov** [comment]
@juslintek It's because the plugin author messed up their folder structure in the `trunk/5.3.4` folder. Check any other release and you will see it has a different structure:

5.3.3:
https://plugins.svn.wordpress.org/google-analytics-dashboard-for-wp/tags/5.3.3/

5.4.4:
https://plugins.svn.wordpress.org/google-analytics-dashboard-for-wp/tags/5.3.4/

Ask the author to release 5.4.5 with the correct folder structure and this will be resolved.

**Comment by strarsis** [comment]
@khromov, @juslintek, @InPhoenity: Have you already created a support ticket in WordPress plugin forum? Otherwise I would create one.

**Comment by InPhoenity** [comment]
@strarsis Not already created, sorry.

**Comment by strarsis** [comment]
@khromov, @InPhoenity:
Apparently the author of GADWP deems the packaging process of wpackagist as the cause:
https://wordpress.org/support/topic/plugin-has-been-deactivated-after-upgrading-to-v5-3-4/
It would be great if this could be resolved with the author.

**Comment by joaquimds** [comment]
It definitely looks to me that the folder structure is wrong for the `5.3.4` release. 

The root of a SVN repository looks like what you find here:

https://plugins.svn.wordpress.org/google-analytics-dashboard-for-wp/

Then in the tags directory, all published versions can be found.

It looks like the version for `5.3.4` contains the whole repository: see https://plugins.svn.wordpress.org/google-analytics-dashboard-for-wp/tags/5.3.4/tags/. This is incorrect.
