### ISSUE TITLE
Keeping removed Tags

### ISSUE THREAD

**Issue by grappler** [outlandishideas/wpackagist#282]
WooCommerce has recently removed all of the tags previous to `3.0` and thus have been removed from . This means that composer can not solve `"wpackagist-plugin/woocommerce": "~2.6",`.

The download links for the older versions still work. https://downloads.wordpress.org/plugin/woocommerce.2.6.14.zip

I wonder if there is a way to keep certain tags permanently if they are older then a week even if they get removed.

**Comment by khromov** [comment]
Currently we only hit the WPorg API for the version lists and versions that disappear from there disappear from WPackagist.
https://github.com/outlandishideas/wpackagist/blob/master/src/Command/UpdateCommand.php#L149

Although it would be possible to keep track of versions over time it would require a lot of additional logic. You are of course welcome to make a PR for this. 

Personally I feel this is not a great move by WooCommerce and that you should give them feedback about this change.

**Comment by grappler** [comment]
Turns out the WooCommerce is on Packigist https://packagist.org/packages/woocommerce/woocommerce

So I could use `"woocommerce/woocommerce": "~2.6"` instead.

**Comment by NoelLH** [comment]
Closing this for now as it's the expected result of a package maintainer pulling a version.
