### ISSUE TITLE
Custom-post-widget plugin ("wpackagist-plugin/custom-post-widget":"3.0.4")

### ISSUE THREAD

**Issue by ketan-chawda** [outlandishideas/wpackagist#285]
Ex : "wpackagist-plugin/custom-post-widget":"3.0.4"
Branch 3.0.4 is giving directories such as trunk and etc which are usually part of dev-trunk branch.
Plugin gets deactivated since custom-post-widget.php is missing in root directory.

Using branch dev-trunk resolves the problem. Ex : "wpackagist-plugin/custom-post-widget":"dev-trunk"

But still, branch 3.0.4 needs to be fixed.

Thanks

**Comment by NoelLH** [comment]
This looks like a publish error by the package maintainer on WordPress.org to me. Version 3.1.5 is fine so closing.
