### ISSUE TITLE
WP Recipe Maker missing 3.1.2 version

### ISSUE THREAD

**Issue by KamWis** [outlandishideas/wpackagist#286]
During today's build I've notice build failed because of missing 3.1.2 version for WP Recipe Maker. The version is available in https://wordpress.org/plugins/wp-recipe-maker/#developers list.

**Comment by khromov** [comment]
Hi @KamWis 

The `3.1.2` version does not seem to be tagged anymore according to the SVN server: http://plugins.svn.wordpress.org/wp-recipe-maker/tags/

Unfortunately, the plugin author can remove tags by deleting them from SVN. This is not a WPackagist problem, but you can email `plugins@wordpress.org` if you want to voice your concerns. Please specify a newer version of the plugin.

**Comment by KamWis** [comment]
That's resolves this issue. Thank you for clarification!
