### ISSUE TITLE
all-in-one-wp-security-and-firewall

### ISSUE THREAD

**Issue by 76mwlaw** [outlandishideas/wpackagist#288]
Updating plugin with composer downloads entire svn vs. latest version of plugin (4.3.7.2). 4.3.7.2 shows up fine on wordpress.org but looking at the trunks on the svn only see up to 4.3.7.1.

**Comment by mrnschrmm** [comment]
I solved the issue for now with using "dev-trunk" as version. The result is a correctly extracted 4.3.7.2 in the plugins folder.

**Comment by MichalOdchazel** [comment]
I have the same problem.

**Comment by ikappas** [comment]
I am experiencing the same issue with this package.  

My `composer.lock` contains the following entry:

```json
        {
            "name": "wpackagist-plugin/all-in-one-wp-security-and-firewall",
            "version": "4.3.7.2",
            "source": {
                "type": "svn",
                "url": "https://plugins.svn.wordpress.org/all-in-one-wp-security-and-firewall/",
                "reference": "tags/4.3.7.2"
            },
            "dist": {
                "type": "zip",
                "url": "https://downloads.wordpress.org/plugin/all-in-one-wp-security-and-firewall.4.3.7.2.zip",
                "reference": null,
                "shasum": null
            },
            "require": {
                "composer/installers": "~1.0"
            },
            "type": "wordpress-plugin",
            "homepage": "https://wordpress.org/plugins/all-in-one-wp-security-and-firewall/"
        },
```

and I can confirm that `https://downloads.wordpress.org/plugin/all-in-one-wp-security-and-firewall.4.3.7.2.zip` contains the whole repository.

Interestingly the main download button has `https://downloads.wordpress.org/plugin/all-in-one-wp-security-and-firewall.zip` without any version and a `development version` is missing.

So this seems to be an issue with the repository itself.

**Comment by ikappas** [comment]
Just opened a ticket at https://wordpress.org/support/topic/wpackagist-package-broken-with-4-3-7-2/

**Comment by khromov** [comment]
The plugin version scheme is not [semver](https://semver.org/)-compatible. Likely same issue as https://github.com/outlandishideas/wpackagist/issues/301#issuecomment-534063188
