### ISSUE TITLE
AMP for WP – Accelerated Mobile Pages not updated

### ISSUE THREAD

**Issue by kevinmrl** [outlandishideas/wpackagist#293]
Hello,

![image](https://user-images.githubusercontent.com/45454204/55468507-6fa8da80-55fb-11e9-85af-76a31a2fdd75.png)

The latest version is visible: 0.9.97.44

Though, it should be

![image](https://user-images.githubusercontent.com/45454204/55468547-8cdda900-55fb-11e9-9be6-47234de17aab.png)

**Comment by khromov** [comment]
This appears to have fixed itself. I will say though, that this versioning scheme does not follow [Semantic Versioning](https://semver.org/) and may not work reliably in WPackagist. Please ask the author to follow semver.
