### ISSUE TITLE
Plugin invisible after install: WP Githuber MD – WordPress Markdown Editor

### ISSUE THREAD

**Issue by bridgeport** [outlandishideas/wpackagist#294]
Thanks for this great resource.

This is the plugin:
https://wordpress.org/plugins/wp-githuber-md/
https://github.com/terrylinooo/githuber-md/
https://wpackagist.org/search?q=wp-githuber-md&type=plugin&search=

It does install...
```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing wpackagist-plugin/wp-githuber-md (1.7.3): Downloading (100%)
Writing lock file
Generating autoload files
```
...but doesn't appear in the list of plugins afterward, so it can't be activated.

Thanks.

**Comment by khromov** [comment]
I don't see any immediate issues with the current version of the plugin. Closing as old issue.
