### ISSUE TITLE
TinyMCE Advanced wrong release

### ISSUE THREAD

**Issue by thomascharbit** [outlandishideas/wpackagist#295]
Hi,

The [TinyMCE Advanced plugin](https://wordpress.org/plugins/tinymce-advanced/) version 5.2.0 available through WPackagist is different from the one from the wp.org website.

There is a typo error in the `tinymce-advanced.php` file, i guess the plugin author re-released it without tagging a new version.

I don't know how you handle this usually? Is it possible to flush it?

Thanks

**Comment by khromov** [comment]
There is a tagged `5.2` and a `5.2.0` version. This is not correct by the author according to semantic versioning, and I'm not sure how Composer deals with this. 

Things you could try:
- Try to clear your local Composer cache - `composer clear-cache` and run `composer install again`.
- If you are currently using the `5.2` release, try specifying `5.2.0` in your `composer.json` (or vice versa).

**Comment by thomascharbit** [comment]
I should have seen it, sorry! thanks.
