### ISSUE TITLE
How to change plugin's language?

### ISSUE THREAD

**Issue by mamoruuu** [outlandishideas/wpackagist#297]
I have a Wordpress website installed and deployed via Composer and the plugins from wpackagist as the dependencies. While Wordpress itself translated to russian, plugins are still in english.

In my case I have these plugins with official russian language support:
- [All In One SEO Pack](https://wordpress.org/plugins/all-in-one-seo-pack/)
- [Caldera Forms](https://wordpress.org/plugins/caldera-forms/)

If I install them via Wordpress UI russian language works perfectly.

How can I enable when plugins installed via Composer?

**Comment by khromov** [comment]
There are multiple approaches. The simplest one is to let WordPress figure out that it has translation updates by not disabling the built-in update function. In that case you will get the translation updates. Then simply persist `wp-content/languages` between releases as you would `/wp-content/uploads`.

Here is a good blog post with some other approaches:
https://bjornjohansen.no/composer-wordpress-translations

Unfortunately, this is not within scope of WPackagist at the moment, but if you're interested in adding this functionality, please create a PR or a new issue with an outline for how to implement it.

**Comment by mamoruuu** [comment]
Thanks a lot, @khromov!
