### ISSUE TITLE
Dependency management is not corrent when using wordpress mirror

### ISSUE THREAD

**Issue by katsar0v** [outlandishideas/wpackagist#298]
Hi guys!

I just installed `WP Mail SMTP by WPForms` via WPackagist, here is the "require" part of my `composer.json` file:

```
"require": {
    "php": ">=7.3",
    "composer/installers": "^1.4",
    "roots/wordpress": "5.2.2",
    "roots/wp-password-bcrypt": "1.0.0",
    "wpackagist-plugin/wp-mail-smtp": "1.5.0"
  },
```

and here is how it looks in composer.lock:

```
{
            "name": "wpackagist-plugin/wp-mail-smtp",
            "version": "1.5.0",
            "source": {
                "type": "svn",
                "url": "https://plugins.svn.wordpress.org/wp-mail-smtp/",
                "reference": "tags/1.5.0"
            },
            "dist": {
                "type": "zip",
                "url": "https://downloads.wordpress.org/plugin/wp-mail-smtp.1.5.0.zip"
            },
            "require": {
                "composer/installers": "~1.0"
            },
            "type": "wordpress-plugin",
            "homepage": "https://wordpress.org/plugins/wp-mail-smtp/"
        }
```

and of course I registered wpackagist as repository :) : 
```
{
      "type": "composer",
      "url": "https://wpackagist.org"
}
```

The problem is that, when I installed the plugin, the plugin has it's own `vendor/` folder. This means the dependencies are kind of redundant. If I have dependencies which repeat in the plugin (e.g. php-jwt or monolog) they would be loaded twice. How can this be fixed so there is no redundancy in the dependencies?

**Comment by khromov** [comment]
Hey @katsar0v ,

This is unfortunately an unsolved problem What WPackagist does is just to take the distribution zip files from `plugins.wordpress.org` and unpacks them into the appropriate directory, allowing you to configure which plugins you want and at which versions. WordPress.org has no official stand on the `vendor/` folder in plugins from my knowledge.

Here is a good article that outlines the issue:
https://wppusher.com/blog/a-warning-about-using-composer-with-wordpress/

I have personally taken a stab at this a while back, you can check out my project here:
https://github.com/khromov/wp-onus

(Unfortunately, my approach requires plugins to specifically support it.)

**Comment by katsar0v** [comment]
Hey @khromov thank you for the update! So basically `WPackagist` is a mirror, but in fact it should be own repository with own maintanance. This sounds.. like a lot of work for the project and also a bit more work for the plugin creators.

**Comment by NoelLH** [comment]
Unfortunately I don't see Wpackagist or similar ever being able to solve this with wide adoption, without a clear stance from the WordPress core team. Will close for now. Please create issues or PRs if anyone has a specific suggestion of what we could do!
