### ISSUE TITLE
Plugin not available (secupress)

### ISSUE THREAD

**Issue by kl3sk** [outlandishideas/wpackagist#300]
My composer update failed due to
```bash
Updating wpackagist-plugin/secupress (1.4.9.2 => 1.4.10): Downloading (failed)    Update failed (The "https://downloads.wordpress.org/plugin/secupress.1.4.10.zip" file could not be downloaded (HTTP/1.1 404 Not Found))
    Would you like to try reinstalling the package instead [yes]?
```

using `dev-trunk` seems to work

**Comment by kl3sk** [comment]
Any update about this issue ?

**Comment by khromov** [comment]
Plugin author didn't release version `1.4.10` properly, it's just an empty folder:
http://plugins.svn.wordpress.org/secupress/tags/1.4.10/

Unfortunately, we can only go by what the WordPress.org API tells us, and it says there is a version 1.4.10 zip. Ask the author to properly upload the next version, and in the meantime, specify the `trunk` version in your `composer.json`.

**Comment by kl3sk** [comment]
Thank you for your feedback.
