### ISSUE TITLE
Wrong version name for wpackagist-plugin/object-sync-for-salesforce

### ISSUE THREAD

**Issue by mariusghitoiu** [outlandishideas/wpackagist#303]
Hi, 

wpackagist-plugin/object-sync-for-salesforce - for this plugin there is a version `1.84` instead of `1.8.4` and composer it always takes this version instead of the latest one which is `1.8.12`. 

Is this something that should be fixed on `wpackagist` or should I report this to plugin repo https://github.com/MinnPost/object-sync-for-salesforce/issues

Thank you!

**Comment by johnbillion** [comment]
This is expected behaviour. `1.84` is higher than `1.8.4`. You should report this to the plugin author.

You can get around this in the meantime by using `^1.8` as your version constraint.
