### ISSUE TITLE
Fail to require plugin "stop-spammer-registrations-plugin"

### ISSUE THREAD

**Issue by yaaax** [outlandishideas/wpackagist#304]
Hi there,
First of all : thanks for this great tool that allows everyone to manage WordPress plugins the "right way"!

I have an issue with the plugin "Stop Spammers"
I did :
`composer require wpackagist-plugin/stop-spammer-registrations-plugin`
and I get :
```[InvalidArgumentException]   Could not find a matching version of package wpackagist-plugin/stop-spammer-registrations-plugin. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (dev).```

I have in my composer.json :
```"minimum-stability": "dev",
"prefer-stable" : true,```

I've tried to remove ~/.composer/cache --> still get the same issue

Any idea what's going on?

**Comment by johnbillion** [comment]
This is working as expected for me so it's unlikely to be an issue with wpackagist. Is this still an issue for you @yaaax ?

**Comment by yaaax** [comment]
Looks ok now on my machine:
```
Using version ^2020.2 for wpackagist-plugin/stop-spammer-registrations-plugin
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing wpackagist-plugin/stop-spammer-registrations-plugin (2020.2): Downloading (100%)
Writing lock file
Generating autoload files
2 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

Issue was probably due to something else.
Thanks for looking at it.
