### ISSUE TITLE
Is uninstall.php of a plugin called when I do a composer remove?

### ISSUE THREAD

**Issue by landwire** [outlandishideas/wpackagist#306]
Hi there,
when plugins are removed with composer remove do they run the uninstall.php script that the plugin supplies? Was just wondering if that is the case or not.
If not, does it cause any problems? I guess one could end up with a bloated DB or lots of options that are not used at all...
Thanks!

**Comment by johnbillion** [comment]
No it doesn't. `uninstall.php` is a WordPress mechanism that runs when you click the "Uninstall" link next to a plugin or when you run `wp plugin uninstall` with WP-CI.
