### ISSUE TITLE
Release not listed for specific plugin

### ISSUE THREAD

**Issue by strarsis** [outlandishideas/wpackagist#308]
A new release (`2.5.15`) of the [WooCommerce Blocks](https://wordpress.org/plugins/woo-gutenberg-products-block/) plugin is not listed on the [wpackagist site](https://wpackagist.org/search?q=woo-gutenberg-products-block&type=any&search=), the latest version there is the previous `2.5.14`. `wpackagist` lags slightly by some hours, but this release doesn't have appeared yet after much longer time than usual.

**Comment by khromov** [comment]
If you search for the package on [the WPackagist website](https://wpackagist.org/search?q=woo-gutenberg-products-block) and press the "Update" button, you can manually refresh the package. I just did that, and it picked up version `2.5.15`. 😄 

<img width="112" alt="Screenshot 2020-04-03 at 17 56 56" src="https://user-images.githubusercontent.com/1207507/78380684-88641b80-75d4-11ea-9185-e33d7c2052bb.png">

**Comment by strarsis** [comment]
@khromov: So the refresh button not only reloads the page but also triggers an update check.

**Comment by khromov** [comment]
That's right! 😊

**Comment by strarsis** [comment]
@khromov: Hmm, it may be a good idea to add a notice/hint to the page so the user knows that this button can be used when the latest release is still missing.

**Comment by strarsis** [comment]
@khromov: I just noticed that even after using that update button, `composer update` still fails to see the new package release (and fails when that version is specified). Is this a caching issue with composer?
