### ISSUE TITLE
Regenerate Thumbnails Issue

### ISSUE THREAD

**Issue by aglipanci** [outlandishideas/wpackagist#313]
Regenerate Thumbnails seems to point to plugin repository on Github here: https://github.com/Automattic/regenerate-thumbnails which doesn't provide with the dist javascript file which is generated after the `yarn build-production` command. Because of that, the plugin doesn't work.

Is there possible to point this to another repository that contains the ready to install plugin?

**Comment by NoelLH** [comment]
@aglipanci as I understand it the wpackagist version always mirrors Wordpress.org.

Are you sure you're pulling that version and not https://packagist.org/packages/viper007bond/regenerate-thumbnails ?

**Comment by aglipanci** [comment]
@NoelLH Not really sure what I did wrong, but I am pretty sure it was cloning the automatic repo. It seems to work pretty well now.
