### ISSUE TITLE
e-junkie plugin does not install files using composer update

### ISSUE THREAD

**Issue by kevinlisota** [outlandishideas/wpackagist#316]
I am attempting to add the following plugin via wpackagist to my WP deployment

`"wpackagist-plugin/e-junkie": "1.2.0"`

composer update only installs readme.md from that plugin, but none of the other files associated to the SVN repository.

I have ~10 other wpackagist plugins in my install that work fine. Not sure how to diagnose or fix this particular one. It is active on wordpress.org

**Comment by khromov** [comment]
@kevinlisota The plugin author is not correctly using the WordPress SVN. The 1.2 release is actually in the `1.0` folder and the `trunk` folder which is supposed to contain the latest release only contains the readme. 🤷
http://plugins.svn.wordpress.org/e-junkie/

To fix this, try setting the version to `1.0`, which is the one that seems to contain their most up-to-date code.
