### ISSUE TITLE
Themeisle-Companion Plugin Could Not Be Downloaded

### ISSUE THREAD

**Issue by ChexWarrior** [outlandishideas/wpackagist#324]
Hey all,

Been getting an issue with the [Themeisle Companion](https://wordpress.org/plugins/themeisle-companion/) plugin when attempting to grab the latest version via a `composer update`.  Here is the error message:
```
 [Composer\Downloader\TransportException]                                                                                           
  The "https://downloads.wordpress.org/plugin/themeisle-companion.2.9.17.zip" file could not be downloaded (HTTP/1.1 404 Not Found)  
```

When I attempt to curl that link or go to it directly it is indeed not there, is this an issue on the WordPress side or something else?  It looks like other plugins I have are present when I visit them at a similar URL (i.e. https://downloads.wordpress.org/plugin/elementor.2.9.14.zip).

Thank you in advance

**Comment by NoelLH** [comment]
This sounds like an issue on the WP side or an error publishing the package @ChexWarrior. Wpackagist just mirrors this stuff so I'll close this for now. Please shout if you find anything that looks like it's not joined up on the mirroring side.
