### ISSUE TITLE
Asking for authentication from wpackageist.org while executing composer update

### ISSUE THREAD

**Issue by nikhil69820** [outlandishideas/wpackagist#326]
While executing composer install/update, it is asking for Authentication but didn't find any option to create an account on wpackagist.org. Please help me on this.

**Comment by NoelLH** [comment]
What's the full error message @nikhil69820? Is it definitely the WordPress package that it relates to? I've had this with GitHub rate limits before.

**Comment by nikhil69820** [comment]
scl000102714:/srv/www/htdocs # composer update

PHP Warning:  PHP Startup: Unable to load dynamic library 'php_openssl.dll' (tried: /usr/lib64/php74/extensions/php_openssl.dll (/usr/lib64/php74/extensions/php_openssl.dll: cannot open shared object file: No such file or directory), /usr/lib64/php74/extensions/php_openssl.dll.so (/usr/lib64/php74/extensions/php_openssl.dll.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

PHP Warning:  Module 'Phar' already loaded in Unknown on line 0

Loading composer repositories with package information

    Authentication required (wpackagist.org):

      Username:

**Comment by NoelLH** [comment]
@nikhil69820 with the new infrastructure unsecure requests are pushed to SSL. It looks like your PHP's SSL is misconfigured based on those warnings, so maybe the problem is that's stopping it from connecting?

**Comment by NoelLH** [comment]
This seems to be working more widely – please reopen with more info if there's an indication it's a Wpackagist bug.
