### ISSUE TITLE
Too many requests. Try again in an hour.

### ISSUE THREAD

**Issue by strarsis** [outlandishideas/wpackagist#339]
Forcing a package update results in a HTTP error: `Too many requests. Try again in an hour.`

**Comment by khromov** [comment]
@NoelLH Potential fix for this issue here:
https://github.com/outlandishideas/wpackagist/pull/340

Should work behind both ALB and ELB (Classic).

**Comment by NoelLH** [comment]
Thanks again @khromov. This looks like it's behaving on staging to me, so rolling out to production now.
