### ISSUE TITLE
Error 404 on download providers

### ISSUE THREAD

**Issue by elvishp2006** [outlandishideas/wpackagist#342]
I'm getting the following error on composer install
```shell
[Composer\Downloader\TransportException]
  The "https://wpackagist.org/p/providers-2019%243c40910145502e7227ac1ff3c013286f003430f223135f9fef3814d928dabca9.json" file could
  not be downloaded (HTTP/2 404 )
```

**Comment by Liombe** [comment]
Hello I'm getting the same error on `composer install` too

**Comment by conradfuhrman** [comment]
Also having the same issue.

**Comment by danielbachhuber** [comment]
Same issue

**Comment by fu-raz** [comment]
I'm having the issue as well. Started a few minutes ago, was working fine before.

**Comment by jcastilloa** [comment]
+1

**Comment by Brandoning** [comment]
Same here

**Comment by jcastilloa** [comment]
There is a mirror that works:

https://wpackagist.wpsv.se/

#336  https://github.com/outlandishideas/wpackagist/issues/336#issuecomment-699192097

**Comment by thefrosty** [comment]
Same here.

**Comment by NoelLH** [comment]
I believe this is fixed now, can anyone confirm?

It looks like there is a race condition with force updates, the logic for which doesn't really make any sense anyway. I think I'm going to have to switch these off for now in the hope of actually having some time off during this holiday..

**Comment by matbrady** [comment]
I'm no longer experiencing the issue 👍

**Comment by danielbachhuber** [comment]
Seems to be working for me too.

**Comment by mahnunchik** [comment]
https://wpackagist.org/ is down for me

**Comment by NoelLH** [comment]
> https://wpackagist.org/ is down for me

Thanks @mahnunchik, we did get an alert for this different issue and a fix should be rolling out depending on DNS caches.
