### ISSUE TITLE
wpackagist-plugin/blog2social 6.5.1 not found

### ISSUE THREAD

**Issue by jamieburchell** [outlandishideas/wpackagist#345]
The blog2social plugin (https://wordpress.org/plugins/blog2social/#description) exists at version 6.5.1 but is not found when using composer:

```
Problem 1
    - The requested package wpackagist-plugin/blog2social 6.5.1 exists as wpackagist-plugin/blog2social[3.1.3, 3.7.0, 3.7.1, 4.0.0, 4.1.0, 4.1.1, 4.2.0, 4.2.1, 4.2.2, 4.3.0, 4.3.1, 4.3.2, 4.3.3, 4.4.0, 4.4.1, 4.5.0, 4.5.1, 4.6.0, 4.7.0, 4.8.0, 4.8.1, 4.8.2, 4.8.3, 4.9.0, 4.9.1, 4.9.2, 5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.0.4, 5.1.0, 5.1.1, 5.1.2, 5.1.3, 5.1.4, 5.2.0, 5.3.0, 5.4.0, 5.4.1, 5.5.0, 5.6.0, 5.6.1, 5.7.0, 5.7.1, 5.7.2, 5.8.0, 5.8.1, 5.9.0, 6.0.0, 6.1.0, 6.1.1, 6.1.2, 6.2.0, 6.3.0, 6.3.1, 6.4.0, 6.4.1, 6.4.2, dev-trunk] but these are rejected by your constraint.
```

It does appear on wpackagist though:

https://wpackagist.org/search?q=blog2social&type=any&search=

> dev-trunk ... 6.4.2 6.5.0 6.5.1

And in the WP SVN repo:

https://plugins.svn.wordpress.org/blog2social/tags/6.5.1/

**Comment by khromov** [comment]
I confirmed that the last two versions are missing in the [package file](https://wpackagist.org/p/wpackagist-plugin/blog2social%245300682d35ca71d2b898280bfc394976add69681c20a45309dc9a42ab55bac43.json) and I don't see any immediate reason why they wouldn't be showing up. They are also visible on the website. Maybe some issue with the JSON file builds?

@jamieburchell 
As a workaround, you can use `dev-trunk` as the version constraint for now.

**Comment by jamieburchell** [comment]
I don't know if this is a clue or remotely relevant but when I searched for the plugin on the wpackagist website the latest version number didn't show on the page until I clicked the little arrow "refresh" icon

**Comment by piscis** [comment]
We have the same problem with other plugins for a couple of weeks now. Sometimes updated plugins are not installable via wppackagist + composer cli. We then hit refresh on the website (version is missing every time) wait for an hour or so and then clear composer cache by entering `composer clear-cache` and `composer update` most of the time it works and it installs the plugin and updates the lock file so we can check in the changes for the deployment.

My bet is that plugin updates in the wp-plugin registry take some time to propagate to wppackagist and after refreshing the plugin on the website it manually it takes a couple of minutes to propagate so composer cli can pick it up. ...

**Comment by jamieburchell** [comment]
Thanks - I did try clearing the composer cache and waiting a while but no luck until the next day. Then a new version was released and it was only available the following day again.

**Comment by piscis** [comment]
For me it took around 2.5 hours from refreshing the wpackagist website manually and then see version 3.51.2 to be able to update mailpoet locally via composer cli from 3.51.1 -> 3.51.2

**Comment by jamieburchell** [comment]
Still seeing this for the blog2social plugin as an example. The plugin was updated from 6.5.4 to 6.5.5 around 7 days according to the Wordpress website, but 6.5.4 was the last version shown on the wpackagist page. After clicking the refresh button, the list of versions immediately updated to including 6.5.5 and after a few hours a composer update pulled down 6.5.5.

**Comment by NoelLH** [comment]
I expect this overlaps with #350 and will benefit from @rasmuswinter's fixes but let's keep it open until we can test that assumption.

I've just added details of the specific bug #368 which is the current root issue blocking a fix release. Pull requests are welcome.

**Comment by NoelLH** [comment]
I've just added this dependency in a test project set to use Staging Wpackagist – having updated its DB – and it worked. So this should be fixed live in the coming hours.
