### ISSUE TITLE
Sporadic error

### ISSUE THREAD

**Issue by strarsis** [outlandishideas/wpackagist#348]
Sometimes, when refreshing a package from the search result list, wpackagist shows an error and then redirects back to the search result list:
````
Warning: Invalid argument supplied for foreach() in /var/www/html/vendor/guzzlehttp/guzzle-services/src/ResponseLocation/JsonLocation.php on line 71
Redirecting to /search?q=gutenberg.
````

**Comment by strarsis** [comment]
Another warning that always occurs after reloading a package (appears on the meta redirect page):
Warning: Invalid argument supplied for foreach() in /var/www/html/vendor/guzzlehttp/guzzle-services/src/ResponseLocation/JsonLocation.php on line 71

**Comment by NoelLH** [comment]
See https://github.com/outlandishideas/wpackagist/issues/363#issuecomment-749432210

**Comment by NoelLH** [comment]
Resolving as per #363
