### ISSUE TITLE
Some plugins are inactive

### ISSUE THREAD

**Issue by strarsis** [outlandishideas/wpackagist#349]
The [Event Post](https://wordpress.org/plugins/event-post/) plugin is listed as inactive, without releases and can't be installed using `composer`:
https://wpackagist.org/search?q=event-post&type=any&search=

**Comment by NoelLH** [comment]
Thanks for the report. I see versions now so am closing this as a likely dupe of known issue #350 so we can keep updates in one place, and have just added details of the specific bug #368 which is the current root issue blocking a fix release. Pull requests are welcome.

Please reopen with more info if there is a distinct ongoing issue and I'm missing something.
