### ISSUE TITLE
Lead Forensics plugin not available

### ISSUE THREAD

**Issue by duff907** [outlandishideas/wpackagist#356]
The lead forensics plugin is not available from wpackagist.

Below is a link to the plugin on the wordpress site

https://wordpress.org/plugins/lead-forensics-roi/

**Comment by NoelLH** [comment]
Thanks for the report. I'm closing this as a dupe of known issue #350 so we can keep updates in one place, and have just added details of the specific bug #368 which is the current root issue blocking a fix release. Pull requests are welcome.
