### ISSUE TITLE
Missing plugin contact form 7

### ISSUE THREAD

**Issue by realitix** [outlandishideas/wpackagist#358]
Hello, this plugin is not available with your repository:

https://wordpress.org/plugins/contact-form-7/

**Comment by realitix** [comment]
My bad, I found it

**Comment by Wtower** [comment]
In case it helps someone in the future, the url is:

https://wpackagist.org/search?q=contact-form-7&type=plugin

For some reason it is not searchable as "contact form 7" but rather as "contact-form-7".
