### ISSUE TITLE
userswp is two versions behind

### ISSUE THREAD

**Issue by penhtech** [outlandishideas/wpackagist#361]
The current version of userswp on wordpress.org is 1.2.2.8 but nothing newer than 1.2.2.6 is on wpackagist.

**Comment by NoelLH** [comment]
Thanks for the report. I'm closing this as a dupe of known issue #350 so we can keep updates in one place, and have just added details of the specific bug #368 which is the current root issue blocking a fix release. Pull requests are welcome.
