### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by penhtech** [outlandishideas/wpackagist#362]
There appear to have been no updates made since Sep. 25. Has this project been abandoned?

**Comment by penhtech** [comment]
OK, there have indeed been more recent updates, but I'm suddenly finding far more out of date plugins than before so the question still stands.

**Comment by khromov** [comment]
The project is not abandoned. There has been a heavy on-going rewrite as well as a [recent code overhaul](https://github.com/outlandishideas/wpackagist/pull/357). Some parts of the new system do no work as well as the old one. Hopefully the stability will improve in the short term. Hang in there!

**Comment by khromov** [comment]
See also this comment for additional background: https://github.com/outlandishideas/wpackagist/issues/350#issuecomment-717740232

**Comment by penhtech** [comment]
Terrific, and keep up the great work! May I suggest that you post a message banner to inform people of this?
