### ISSUE TITLE
Glimpse of guzzlehttp error before redirect

### ISSUE THREAD

**Issue by abdusfauzi** [outlandishideas/wpackagist#363]
When I manually press update to refresh certain plugin version, there was this 1s error display as per screenshot.

<img width="916" alt="Screenshot 2020-11-24 at 22 34 11" src="https://user-images.githubusercontent.com/1118229/100109070-6fcbad00-2ea6-11eb-94f2-1428857b1a72.png">

**Comment by NoelLH** [comment]
This logic should be completely replaced with Ras's Nov fixes once they are out, but will leave this one open until we can validate that assumption on Staging.

**Comment by NoelLH** [comment]
Same as #348 but will keep open for now

**Comment by NoelLH** [comment]
Confirmed on [Staging](https://staging-wpackagist.out.re) that this scenario now returns only Symfony's expected redirect metadata as the body with the 302 redirect response:

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="0;url='/search?q=1stpaygateway-for-woocommerce'" />

        <title>Redirecting to /search?q=1stpaygateway-for-woocommerce</title>
    </head>
    <body>
        Redirecting to <a href="/search?q=1stpaygateway-for-woocommerce">/search?q=1stpaygateway-for-woocommerce</a>.
    </body>
</html>
```

Should be live soon.
