### ISSUE TITLE
wpackagist-plugin/polldaddy doesn't exist as 2.2.1 

### ISSUE THREAD

**Issue by IfElseRun** [outlandishideas/wpackagist#367]
When i refreshed wpackagist-plugin/polldaddy it showed 2.2.1 but when  I am trying to update it does not show the version.

**Comment by NoelLH** [comment]
Thanks for the report. I'm closing this as a dupe of known issue #350 so we can keep updates in one place, and have just added details of the specific bug #368 which is the current root issue blocking a fix release. Pull requests are welcome.
