### ISSUE TITLE
Wrong version sorting order

### ISSUE THREAD

**Issue by coreyworrell** [outlandishideas/wpackagist#375]
wpackagist has some issues with sorting version numbers from different formats. Example: https://wpackagist.org/search?q=wpdatatables&type=plugin&search= (the first result, wpdatatables).

You'll see that 2.013 is showing as the latest version, after 2.1.5. This is probably because PHP's built in `version_compare` function thinks 2.013 is greater than 2.1.5. Perhaps there is another compare method that could work for these edge cases, as it seems many plugins don't have consistent versioning formats.

**Comment by NoelLH** [comment]
@coreyworrell I don't think this is specifically down to that PHP method, this is simply how [SemVer](https://semver.org/) works. I don't think the order is wrong and I don't see how we could accommodate this mistake without breaking packages that have correct versioning.

If you look at the [Subversion tags](https://plugins.svn.wordpress.org/wpdatatables/tags/) you can see the vendor has mistakenly published a 'wrong' tag 2.013 as well as the 'right' one 2.0.13. The same apparent mistake is also repeated in the tag's `readme.txt`, meaning that even if we expanded Wpackagist's scope to trying to find such errors, there is no indication we could use to detect in a systematic way that it's unintentional.

Thinking about the general case of how actual SemVer, or systems close to it, work: I _think_ leading zeroes within `X.Y.Z` parts `Y` and `Z` are valid – I'm reading SemVer spec point (2) as only prohibiting zeroes that lead the whole version before `X`, though not 100% on this, but in any case plenty of projects _do_ intentionally use leading zeroes in their middle numeric pieces. So it would be probably-valid and definitely-common to publish versions like:

* 2.0
* 2.0.1
* ...
* 2.0.13
* 2.1.0
* ...
* 2.1.9
* ...
* 2.012.0
* ...
* 2.013

Minor version 13 comes after minor version 0 regardless of the prefix, and it is important to be able to distinguish between the minor and patch components purely based on the dots. So I don't think there is a feasible way we could 'correct' the ordering you've highlighted – it is working as designed.

I think the right fix is for the package maintainer to un-publish the incorrect tag.

**Comment by coreyworrell** [comment]
Oh yes, that makes a lot of sense to allow leading zeros like that for each
part of the version. Thank you. I’ve opened a ticket with them to remove
the wrong version from their repo.
