### ISSUE TITLE
WP Table Builder is not available

### ISSUE THREAD

**Issue by DMBarber** [outlandishideas/wpackagist#377]
I have verified the plugin is available at wordpress.org for [WP Table Builder](https://wordpress.org/plugins/wp-table-builder/) but it does not show when searching

**Comment by fschroiff** [comment]
It's there now, you should use the URL-slug `wp-table-builder` when searching. 

https://wpackagist.org/search?q=wp-table-builder&type=any&search=

**Comment by NoelLH** [comment]
Assuming this was new & a refresh hadn't been done
