### ISSUE TITLE
Plugin not showing up at wpackagist.org - how to submit a plugin?

### ISSUE THREAD

**Issue by Saboteur777** [outlandishideas/wpackagist#378]
I published a plugin to the WordPress Plugin Repository a couple of months ago but it still does not show up when I am searching for it at wpackagist.org. 

Should be something changed in the plugin, or is this a bug?

**Comment by khromov** [comment]
Hey @Saboteur777 

The process for adding plugins is automated.

Can you tell me the name and URL of your plugin on the WordPress Plugin Repository, so that we can check why your plugin is not available.

**Comment by Saboteur777** [comment]
The plugin name is Utánvét Ellenőr: https://wordpress.org/plugins/uv-b-connector-for-woocommerce/

**Comment by khromov** [comment]
@Saboteur777 The plugin is available:
https://wpackagist.org/search?q=uv-b-connector-for-woocommerce&type=any&search=

You can use `wpackagist-plugin/uv-b-connector-for-woocommerce` to install it.

Unfortunately we lack the technology to search for plugin titles in WPackagist 😅, you can only search for the plugin slug.

**Comment by Saboteur777** [comment]
Thanks a lot! :)
