### ISSUE TITLE
Save SVG 1.9.9 seems broken.

### ISSUE THREAD

**Issue by Kcharle** [outlandishideas/wpackagist#379]
Hi,

I pulled `"wpackagist-plugin/safe-svg":"1.9.9"` into my repo and it seems broken, it just pulls in an empty `/lib/vendor/bin` folder. `"wpackagist-plugin/safe-svg":"1.9.8"` works fine though!.

Not sure if this is an issue on your end or the Wordpress plugin directory side, but figured I would mention it.

**Comment by NoelLH** [comment]
@Kcharle is this still having issues? It sounds like an upstream publishing issue to me but looking at the Subversion repo the two tags look similar now, so maybe the plugin author re-published v1.9.9 and fixed it?

**Comment by NoelLH** [comment]
Closing for now – please shout if there's an ongoing issue that doesn't look like it's with the package published on svn.
