### ISSUE TITLE
Cookie Law Info is broken

### ISSUE THREAD

**Issue by svebal** [outlandishideas/wpackagist#380]
the entry in my composer.json: `"wpackagist-plugin/cookie-law-info":"1.9.5"`

command: `composer update`

log output in terminal:
```Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package wpackagist-plugin/cookie-law-info could not be found in any version, there may be a typo in the package name.

```

**Comment by NoelLH** [comment]
This seems to work for me now so I think it was most likely a loading blip on one side or the other (I'm going to raise potentially beefing up the compute power for the site soon) or a new version that hadn't been part of an update or manual refreshed yet.

Please shout if you think there is an ongoing issue relating to this one @svebal
