### ISSUE TITLE
Can't download plugin advanced-custom-fields-table-field

### ISSUE THREAD

**Issue by robmeijerink** [outlandishideas/wpackagist#383]
When trying to install another dependency with Composer. It gives me this error:

  [Composer\Downloader\TransportException]
  The "https://wpackagist.org/p/wpackagist-plugin/advanced-custom-fields-table-field%24151602dfd96c576769e853629d3b52
  42c00057b6270a079007b62ef2f3fc8def.json" file could not be downloaded (HTTP/2 404 )

It used to work fine. Does anyone know how to fix it? When i remove this dependency from my composer.json, everything works fine.

**Comment by fschroiff** [comment]
Duplicate of https://github.com/outlandishideas/wpackagist/issues/381
