### ISSUE TITLE
[Bug] SVN rate limited - Unexpected HTTP status 429 'Too Many Requests'

### ISSUE THREAD

**Issue by EvanHerman** [outlandishideas/wpackagist#396]
I have a number of builds on CircleCI where we install a few plugins via `wpackagist-plugin`. When we get to WooCommerce, we hit a 429 error with the following vague error:

```bash
svn: E175002: Unexpected HTTP status 429 'Too Many Requests' on '/!svn/rvr/2476528/woocommerce/trunk'
```

I've waited about 24 hours and re-ran the job but it's still returning with a 429. From a bit of research, it looks like we can get around this with the `---ignore-externals` flag. [source](https://meta.trac.wordpress.org/ticket/4869#comment:1)

Is this something that can be tweaked here? Or is there another workaround that I've missed? I'm not too familiar with the code base of wpackagist.

![image](https://user-images.githubusercontent.com/5321364/108242835-60fa3c80-711b-11eb-8d81-62ff506ad421.png)

**Comment by EvanHerman** [comment]
Waited 48 hours and re-ran the job and things are now passing. I guess in future I'll just have to wait 24-48 hours. Closing this out.

**Comment by khromov** [comment]
@EvanHerman

Something is a bit non-standard in your setup because typically Composer should download the prebuilt zip files from the WordPress.org CDN and not check out packages from Subversion at all. Are you possibly using the `--prefer-source`-flag? If not, do you see any errors about "unzip" not working when you run the `composer install` command? This is a common error that results in a SVN checkout instead.

**Comment by EvanHerman** [comment]
@khromov No, we're just running `composer install` in our build. You can see our build configuration here: https://github.com/godaddy-wordpress/go/blob/master/.circleci/config.yml#L277

I did hit this 429 again, but after 2 days it has not resolved itself. It sounds like something is forcing it to checkout from SVN directly, instead of hitting the CDN.

**Comment by EvanHerman** [comment]
I just ssh into the build container and ran `composer clear-cache`. I'm not sure if that's what has resolved it, but it seems to be fine again.
