### ISSUE TITLE
Please add flickr-badges-widget

### ISSUE THREAD

**Issue by hasandiwan** [outlandishideas/wpackagist#411]

**Comment by NoelLH** [comment]
Hey @hasandiwan, as noted on the results page a plugin needs to be active on WordPress.org before it can be picked up. Unless I'm missing something this is [not the case](https://wordpress.org/plugins/search/flickr+badges+widget/)?

I can see there are svn tags published but it looks like the author may need to finish submission to the plugins repository or approval by WordPress.org may be pending.

**Comment by hasandiwan** [comment]
I use it on my existing Wordpress site -- on Bluehost -- that I'd like to
migrate to Heroku using your composer infrastructure.

**Comment by NoelLH** [comment]
> I use it on my existing Wordpress site -- on Bluehost -- that I'd like to migrate to Heroku using your composer infrastructure.

It sounds like maybe it's been un-published by the author @hasandiwan. Have you tried contacting them? Does your existing install point to a working Wordpress.org page when you click through for plugin details?

**Comment by hasandiwan** [comment]
It seems that I had paid for the plugin, therefore it isn't composer-installable.

**Comment by NoelLH** [comment]
Thanks for confirming @hasandiwan – it may be the publisher could use https://github.com/cedaro/satispress or similar.
