### ISSUE TITLE
Update = Something went wrong.

### ISSUE THREAD

**Issue by gsc89** [outlandishideas/wpackagist#417]
Tried clicking update / refresh on a a couple of repo's and all of them return: `Something went wrong.` 

A new version of a plugin was released 30 minutes ago and the update isn't available yet so this. 

I tried from this URL : https://wpackagist.org/search?q=wpforo&type=any&search= 

Clicking on update for "wpforo" the others gave me the same thing.

**Comment by NoelLH** [comment]
Thanks @gsc89, we had some errors our side too following some DB maintenance, and are working on a fix.

**Comment by NoelLH** [comment]
A temporary change to the database should have sorted this a little while back, and a permanent fix in the app's config is now live.
