### ISSUE TITLE
ACF Content Analysis for Yoast SEO

### ISSUE THREAD

**Issue by bedrijfsportaal** [outlandishideas/wpackagist#419]
Unable to locate the plugin, see https://wordpress.org/plugins/acf-content-analysis-for-yoast-seo/

**Comment by giuliolastra** [comment]
You can find it here: [https://wpackagist.org/search?q=acf-content-analysis&type=any&search=](https://wpackagist.org/search?q=acf-content-analysis&type=any&search=)

`"wpackagist-plugin/acf-content-analysis-for-yoast-seo":"3.0.1"`
