### ISSUE TITLE
No latest version of plugin

### ISSUE THREAD

**Issue by mahnunchik** [outlandishideas/wpackagist#421]
No latest `1.0.16` version of `travelpayouts` plugin here https://wpackagist.org/search?q=travelpayouts&type=plugin&search=

https://wordpress.org/plugins/travelpayouts/

**Comment by NoelLH** [comment]
This looks to be there now @mahnunchik. You can always request a fetch of a newly published version before the scheduled job runs using the refresh icon in the table.
