### ISSUE TITLE
Plugin is not updated (also not manually)

### ISSUE THREAD

**Issue by strarsis** [outlandishideas/wpackagist#439]
@NoelLH: The [`Gutenberg` plugin](https://wordpress.org/plugins/gutenberg/) [on wpackagist](https://wpackagist.org/search?q=gutenberg&type=plugin&search=#:~:text=Plugin-,gutenberg) is not updated to its latest release `12.5.3` (at time of writing), even with a manual update (refresh button). The release of version `12.5.3` [already happened some time ago](https://wordpress.org/plugins/gutenberg/#:~:text=12.5.3-,Last%20updated%3A,-8%20hours%20ago).

The previous release `12.5.2` is listed and can be installed by `composer`. But the latest release `12.5.3` is neither listed nor can it be installed by `composer` (it can't be found by `composer`).

Tags for Gutenberg plugin in plugin SVN repository: https://plugins.svn.wordpress.org/gutenberg/tags/

**Comment by strarsis** [comment]
`12.5.3` is now listed and available as release. But this doesn't indicate that the manual update is correctly working.

**Comment by strarsis** [comment]
@NoelLH: Updating another plugin worked today ([`advanced-gutenberg`](https://wordpress.org/plugins/advanced-gutenberg/)).
So the issue seems to be resolved?

**Comment by NoelLH** [comment]
Hey @strarsis, I've not changed anything between those dates so I'm not sure what happened honestly. I've seen things go odd sometimes and updates not be picked up if there's a mismatch in the SVN metadata, but I think maintainers can re-publish existing tags, so not sure I'll be able to trace that back to confirm either way now. There aren't any app error logs corresponding to when you had issues.

I'll close this for now, but please shout if you see any more signs of potential problems with this.
