### ISSUE TITLE
HubSpot

### ISSUE THREAD

**Issue by Gneco** [outlandishideas/wpackagist#448]
https://wordpress.org/plugins/leadin/
this is not available on wpackagist.org

**Comment by NoelLH** [comment]
Hi @Gneco – this shows for me: https://wpackagist.org/search?q=leadin&type=plugin&search=

You currently need to search for the 'slug' (the bit in the URL) to find some packages – in this case `leadin`. There's [discussion here](https://github.com/outlandishideas/wpackagist/discussions/80) about improving this but it's not been narrowed down to a specific enhancement issue as yet.
