### ISSUE TITLE
Relevanssi version mismatch

### ISSUE THREAD

**Issue by marcbelletre** [outlandishideas/wpackagist#467]
The current version of Relevanssi is 4.16.0.

<img width="1009" alt="Capture d’écran 2022-07-04 à 14 57 28" src="https://user-images.githubusercontent.com/6853334/177159675-2a83097f-3c03-4454-9c61-3c5d4682c51e.png">

When I install it through composer it shows version 4.16.0.

```
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing wpackagist-plugin/relevanssi (4.16.0): Extracting archive
 ```

But when I go to the Wordpress dashboard it says that the installed version is 4.15.0.

<img width="1862" alt="Capture d’écran 2022-07-04 à 14 59 43" src="https://user-images.githubusercontent.com/6853334/177160025-4f04513e-c51b-4179-b6fb-a429a9b61eab.png">

The main plugin file from the downloaded directory indeed shows version 4.15.0:

```php
<?php
/**
 * Relevanssi
 *
 * /relevanssi.php
 *
 * @package Relevanssi
 * @author  Mikko Saari
 * @license https://wordpress.org/about/gpl/ GNU General Public License
 * @see     https://www.relevanssi.com/
 *
 * @wordpress-plugin
 * Plugin Name: Relevanssi
 * Plugin URI: https://www.relevanssi.com/
 * Description: This plugin replaces WordPress search with a relevance-sorting search.
 * Version: 4.15.0
 * Author: Mikko Saari
 * Author URI: http://www.mikkosaari.fi/
 * Text Domain: relevanssi
 * License: GPLv2 or later
 * License URI: http://www.gnu.org/licenses/gpl-2.0.html
 */
```

**Comment by NoelLH** [comment]
I'm a bit short on time to look at the specifics of this one, but usually when we've seen this before it's an issue with the Subversion repository data/tags the developer has sent to WordPress's SVN repo. I think this can sometimes be patched by them after the fact for the same version but not 100%.

**Comment by NoelLH** [comment]
There have been a few releases since this, so I hope it will have resolved itself. Please reopen if not.
