### ISSUE TITLE
content-protector current version is 3.5.5.5.2 on wordpress but 3.5.5.2 on wpackagist

### ISSUE THREAD

**Issue by rhaft** [outlandishideas/wpackagist#473]
Unable to update to the current wordpress.com version of **content-protector** using composer and wpackagist-plugin. There is a mismatch between the plugin developer's version numbers and versions tracked on wpackagist.

Does wpackagist support version numbers that use a major version and four minor versions, i.e. `X.y.y.y.y` ?

**Comment by khromov** [comment]
Think this is the same problem as https://github.com/outlandishideas/wpackagist/issues/399#issuecomment-808261543

WPackagist uses `composer/semver` package under the hood to determine the version and [semver technically only has an x.y.x format](https://semver.org/#semantic-versioning-specification-semver).

**Comment by NoelLH** [comment]
I'll close this as a duplicate for now as it's currently a known limitation that this isn't supported. If anybody has ideas for an easy way to address this besides packages avoiding 5+ version parts, I'm happy to discuss further on the open issue.
