### ISSUE TITLE
rollback-update-failure version mismatch

### ISSUE THREAD

**Issue by tricarte** [outlandishideas/wpackagist#480]
Latest version of rollback-update-failure plugin listed in wpackagist.org is 3.3.2. But in downloads.wordpress.org it is 3.3.1.  My relevant composer.json entry is `"wpackagist-plugin/rollback-update-failure":"^3.1.1"`. With this entry, `composer update` fails as it is trying to download v3.3.2 that does not exist in downloads.wordpress.org. If I remove the caret, `composer update` works as usual.

CHANGELOG.md of rollback-update-failure lists 3.3.2 as unreleased in its github repo.

Edit: I also have these entries in composer.json
```
    "minimum-stability": "dev",
    "prefer-stable": true,
```

**Comment by NoelLH** [comment]
@tricarte It looks like maybe this was a timing issue with the plugin's release processes and/or the readme is out of date.

Everything seems to agree now that 4.0.0 is the latest (tagged yesterday) – [WP plugins directory](https://wordpress.org/plugins/rollback-update-failure/), [Wpackagist](https://wpackagist.org/search?q=rollback-update-failure&type=any&search=#) and the repo's [tags](https://github.com/WordPress/rollback-update-failure/tags), even though the [changelog](https://github.com/WordPress/rollback-update-failure/blob/435639ab03005ce2fa36773dd96e320909af41ab/CHANGELOG.md) starts "[unreleased]", so I think maybe this is a typo?

**Comment by tricarte** [comment]
Thanks for informing. The issue is gone.
