### ISSUE TITLE
dynamic-widgets plugin package missing

### ISSUE THREAD

**Issue by khromov** [outlandishideas/wpackagist#491]
Started getting this error:

```
Problem 1
    - Root composer.json requires wpackagist-plugin/dynamic-widgets 1.5.16, found wpackagist-plugin/dynamic-widgets[1.5.16] in the lock file but not in remote repositories, make sure you avoid updating this package to keep the one from the lock file.
```

The package does exist with the listed version:
https://wpackagist.org/search?q=dynamic-widgets

But repo JSON returns 404:
https://repo.packagist.org/p2/wpackagist-plugin/dynamic-widgets~dev.json ( When `"minimum-stability": "dev",`)
https://repo.packagist.org/p2/wpackagist-plugin/dynamic-widgets.json (Default settings)

**Comment by NoelLH** [comment]
@khromov It looks like the plugin may have been un-published from WordPress.org and thus is marked inactive (red X for that column in the search you linked).

Following the note below the results, I tried the URL `https://wordpress.org/plugins/dynamic-widget/` directly and it just 301-redirects me to a keyword-based search for similar but different plugins.

I don't know where to find any active version, so I'm not sure who the vendor is or how to check if the plugin has a new name.
