### ISSUE TITLE
Referencing a plugin version by Subversion revision number

### ISSUE THREAD

**Issue by rkaiser0324** [outlandishideas/wpackagist#497]
Sometimes a plugin version has been published, but after some time that version disappears from the wpackagist listing, since the tag has been dropped from the [plugins subversion repository](https://plugins.svn.wordpress.org/redux-framework/tags/).  While this is listed as a possibility in [this link](https://developer.wordpress.org/plugins/wordpress-org/how-to-use-subversion/#delete-old-versions), that seems a horrible thing for WordPress to allow as it means clean installations might break with no warning if the plugin author has decided to delete an old version that you reference in `composer.json`. Separately I am inquiring with WordPress to see if their policy allowing this can be changed going forward.

One example is of this happening is with the plugin redux-framework.  Last time I checked (perhaps last year, maybe earlier), v4.1.24 was there.  I checked today, and the versions available start at v4.3.0.

![image](https://user-images.githubusercontent.com/1090569/234911108-a29524da-ef2c-421b-bc76-0c6c8cecef64.png)

As a workaround I could look up the SVN revision number that corresponds to v4.1.24.  Is there a syntax I can use in `composer.json` that can allow wpackagist to use that revision number directly, rather than relying solely on the published tags?

**Comment by NoelLH** [comment]
Hey @rkaiser0324, I definitely agree it would be good if plugin authors avoided that!

Unfortunately I think it might be quite a lot of complexity for a fairly rare case to support specifying versions in a distinct way. I'm also not super clear how it would work as I haven't used svn outside of any other situation but WP plugins. Do you think it's common for authors to delete a tag but leave its reference in a way that's easy to identify?

**Comment by NoelLH** [comment]
I'm going to close this for now as I'm unclear if there could ever be a way for us to have the metadata to work around it, but please feel free to reopen if somebody has one.
