### ISSUE TITLE
Use CDN such as CloudFlare?

### ISSUE THREAD

**Issue by tamlyn** [outlandishideas/wpackagist#50]
Seems like enabling CloudFlare would be a quick and easy way to improve download speeds. I've not used it much before though. Any possible issues? Or better suggestions?

**Comment by lavoiesl** [comment]
@tamlyn Any update on this?

**Comment by tamlyn** [comment]
I did some testing and you're right it doesn't seem to be working. The config looks right though. Need to dig deeper.

**Comment by lavoiesl** [comment]
Like I said, the cache headers are not said properly, I would need to see the config to help you. Add the nginx config file in this repository so it can be looked at, PR, etc.

**Comment by tamlyn** [comment]
I had added the caching rules in the CloudFlare control panel as I assumed that would override anything set in Nginx. But it seems not. I've now added expires headers in Nginx as well and they're coming through on both wpackagist.org and test.wpackagist.org.

**Comment by lavoiesl** [comment]
My tests indicate roughly 40% better performance. I will switch all my configs to test.wpackagist.org and will see what happens.

```
$ siege -H 'Accept-Encoding: gzip, deflate' -b -c 20 -r 20 'http://wpackagist.org/p/providers-2015-03$791e739fd0aeea53151b6622dae0871d68578cea241df0ca240735d3fed643c9.json'

** SIEGE 3.0.5
** Preparing 20 concurrent users for battle.

Transactions:                    400 hits
Availability:                 100.00 %
Elapsed time:                  15.91 secs
Data transferred:              58.98 MB
Response time:                  0.73 secs
Transaction rate:              25.14 trans/sec
Throughput:                     3.71 MB/sec
Concurrency:                   18.43
Successful transactions:         400
Failed transactions:               0
Longest transaction:            1.72
Shortest transaction:           0.63

$ siege -H 'Accept-Encoding: gzip, deflate' -b -c 20 -r 20 'http://test.wpackagist.org/p/providers-2015-03$791e739fd0aeea53151b6622dae0871d68578cea241df0ca240735d3fed643c9.json'

** SIEGE 3.0.5
** Preparing 20 concurrent users for battle.

Transactions:                    400 hits
Availability:                 100.00 %
Elapsed time:                  11.04 secs
Data transferred:              54.72 MB
Response time:                  0.51 secs
Transaction rate:              36.23 trans/sec
Throughput:                     4.96 MB/sec
Concurrency:                   18.57
Successful transactions:         400
Failed transactions:               0
Longest transaction:            1.23
Shortest transaction:           0.32
```

**Comment by tamlyn** [comment]
I've just turned CloudFlare on for the main `wpackagist.org` domain.

**Comment by NoelLH** [comment]
I think we can close this as done, and superseded by the new infra
