### ISSUE TITLE
Version 2.27.7 does not exist 

### ISSUE THREAD

**Issue by ico3iain** [outlandishideas/wpackagist#502]
The latest version is Version:2.17.10
https://wordpress.org/plugins/bbpress-notify-nospam/

https://wpackagist.org/search?q=bbpress-notify-nospam&type=any&search=
Thanks

**Comment by ico3iain** [comment]
https://wpackagist.org/search?q=bbpress-notify-nospam&type=any&search=

**Comment by NoelLH** [comment]
Hey @ico3iain, thanks for reporting.

This looks to be a mistake in the Subversion things the plugin author has uploaded. I would suggest letting them know so they can consider tidying it up.

You can see here that there is a tag published as 2.27.7, even though its contents say the version is 2.17.7: https://plugins.svn.wordpress.org/bbpress-notify-nospam/tags/2.27.7/bbpress-notify-nospam.php
