### ISSUE TITLE
aam-complete-package not showing

### ISSUE THREAD

**Issue by mmorris8** [outlandishideas/wpackagist#513]
Plugin is visible on wordpress. Will keep poking around.

**Comment by NoelLH** [comment]
I think that might be the name for the paid variant? I can't find that listed on WordPress.org and I don't think we have a way to handle premium plugins inside Wpacakagist.

The free version has a different name / "slug" and can be found at https://wpackagist.org/search?q=advanced-access-manager&type=plugin

**Comment by mmorris8** [comment]
Well that complicates things.  Hmm. The site I'm being put in charge in has multiple paid plugins. Anyway, nothing more to do here. Thank you for your time.
