### ISSUE TITLE
wpackagist/duo-wordpress version problem.

### ISSUE THREAD

**Issue by jeremyzahner** [outlandishideas/wpackagist#60]
I updated "wpackagist/duo-wordpress": "~2.4" to "wpackagist/duo-wordpress": "~2.4.1" in my composer.json.

On "composer update" i get the following error.

"The requested package wpackagist/duo-wordpress could not be found in any version, there may be a typo in the package name."

When checking on wpackagist, i see that the version 2.4.1 has been published.
I also upgraded the site to wp 4.1 already.

**Comment by Rarst** [comment]
Try `wpackagist-plugin/duo-wordpress`, I think there was something about disabling old vendor namespace recently.

**Comment by jeremyzahner** [comment]
@Rarst Smooth, that went quite good. Thanks for the advice. Now just for my understanding. What was the issue exactly?

**Comment by jeremyzahner** [comment]
Solved.

> The old vendor prefix wpackagist is now removed in favour of wpackagist-plugin.
> http://wpackagist.org/

**Comment by Rarst** [comment]
This probably needs to be bigger, bolder, and with blinking background on home page. :) cc @tamlyn

**Comment by lavoiesl** [comment]
```html
<blink><marquee><sarcasm>LIKE THIS?</sarcasm></marquee></blink>
```
