### ISSUE TITLE
"homepage" switches between http to https all the time

### ISSUE THREAD

**Issue by khromov** [outlandishideas/wpackagist#63]
We're using wpackagist in a team of a few people. Frequently, when running composer update, wpackagist changes the "homepage" url scheme of all plugins from http to https. When another user runs composer update, it changes back to http, thus creating large diff files.

We have not been able to figure out why this is happening, hoping someone has had this issue...

**Comment by lavoiesl** [comment]
Are you using a local installation of WPackagist or http://wpackagist.org/packages.json ?

**Comment by khromov** [comment]
@lavoiesl I believe we are using the version on wpackagist.org - we haven't setup WPackagist to run locally.

**Comment by lavoiesl** [comment]
Ok, but I’m not sure I understand what your problem is, can you try to re-explain the steps to reproduce it?

**Comment by khromov** [comment]
About an hour ago I ran:

    composer update privatenamespace/privaterepo.
 
(A GitHub-hosted private repo.)

Here is what the diff looked like (the wpackagist part). Note that I hadn't even attempted to update a wpackagist package.

![capturfiles_14](https://cloud.githubusercontent.com/assets/1207507/6023253/ba0f582e-abc3-11e4-8c56-f80303f7f7c8.png)

This happens once or twice a week for us.

**Comment by lavoiesl** [comment]
This is very odd, you are having an old version of wpackagist. `replace` was removed in #49, last December. Are you sure you are not using some kind of cache in front of it ? Try emptying your `~/.cache/composer` directory.

**Comment by khromov** [comment]
Hey there @lavoiesl , 

We have synced our composer version and cleared composer cache, now we don't get these weird diffs any more. Thanks!
