### ISSUE TITLE
Deploying new version of the code

### ISSUE THREAD

**Issue by louim** [outlandishideas/wpackagist#66]
Hello, 

I think the site in under @tamlyn control, I would like to know if you could deploy the new code?

Thank you very much.

**Comment by tamlyn** [comment]
I'm on it.

**Comment by tamlyn** [comment]
The server that hosts wpackagist.org is being retired but there are a couple of issues with the new server which are holding up the migration. Will keep you posted.

**Comment by louim** [comment]
Thanks for the update!

**Comment by lavoiesl** [comment]
Do you need hosting?

**Comment by tamlyn** [comment]
Deployed! Finally.

**Comment by lavoiesl** [comment]
:+1:
