### ISSUE TITLE
New theme directory design breaking updates

### ISSUE THREAD

**Issue by tamlyn** [outlandishideas/wpackagist#68]
The WordPress theme directory site has been redesigned https://wordpress.org/themes/

The current update process tries to fetch the `https://wordpress.org/themes/[theme name]/developers/` which is no longer a valid URL. The result is that any theme that has published an update since the new design was rolled out (some time in February) is being marked as inactive in our database.

**Comment by Rarst** [comment]
What info do you need from it? While back I had spent some time on pretty thorough abstraction for their APIs, including themes. See https://github.com/Rarst/wporg-client

**Comment by tamlyn** [comment]
I'm not sure what its used for, need to check the code. Thanks for the suggestion.

**Comment by lavoiesl** [comment]
Seems wporg-client would do the trick. If it misses something, it would probably be easier to just patch that anyway. However, I am not available this week.

**Comment by tamlyn** [comment]
Tentative implementation of version fetching from WP API on branch [wporg](https://github.com/outlandishideas/wpackagist/tree/wporg). Requires my patched version of `rarst/wporg-client` see rarst/wporg-client#1.

**Comment by Rarst** [comment]
PR merged into client, cheers. :)

**Comment by tamlyn** [comment]
Fix is now deployed. All affected themes should be reactivated and updated with latest versions.

**Comment by tdg5** [comment]
Awesome, thanks for getting this taken care of! @tamlyn

**Comment by lavoiesl** [comment]
@tamlyn I can’t see your fix, did you push it to master?

**Comment by tamlyn** [comment]
It was on a branch but I've now merged it.
