### ISSUE TITLE
WP Front End Editor plugin missing

### ISSUE THREAD

**Issue by khromov** [outlandishideas/wpackagist#70]
```
"wpackagist-plugin/wp-front-end-editor": "1.0.4"
```

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package wpackagist-plugin/wp-front-end-editor could not be found in any version, there may be a typo in the package name.
```

But it is available on WPackagist:  
http://wpackagist.org/search?q=wp-front-end-editor&type=any&search=

**Comment by tamlyn** [comment]
We had an issue with the build process. Since the server move it's been outputting the updated files to the wrong directory! Sorry about that, and thanks for taking the time to report the problem.

**Comment by khromov** [comment]
@tamlyn Wonderful, thanks! :+1:
