### ISSUE TITLE
Can't update to better-wp-security 4.6.10

### ISSUE THREAD

**Issue by mrobit** [outlandishideas/wpackagist#71]
Sorry if this is something that I'm missing or not doing right, but I've tried clearing composer cache, deleting composer/re-installing, setting `--prefer-source`, etc. but I can't get this package to update to the latest tag.

Any suggestions?

**Comment by tamlyn** [comment]
We had an issue with the build process. Since the server move it's been outputting the updated files to the wrong directory! Sorry about that, and thanks for taking the time to report the problem.
