### ISSUE TITLE
Problem updating to custom-post-type-ui, version 1.0.3 and 1.0.4

### ISSUE THREAD

**Issue by egifford** [outlandishideas/wpackagist#72]
Hey WPackagist,

Awesome service!  We've been using it for about a year and it makes maintaining WordPress so easy.

I don't know if it is appropriate to report this here, but we're having trouble updating one plugin: custom-post-type-ui.

I've got a report going for the plugin:
https://wordpress.org/support/topic/composer-installs-cant-install-versions-103-or-104

We can install 1.0.2 just fine with:
"wpackagist-plugin/custom-post-type-ui" : "1.0.2"

But 1.0.3 or 1.0.4 fails with:
"Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - The requested package wpackagist-plugin/custom-post-type-ui 1.0.4 could not be found."

I've seen another post were someone on the team was able to verify the status of particular plugin and version.  I didn't know if that was possible in this case: just to verify that the status of the plugin looks ok from wpackagists point of view.

If not and this is out of scope, just let me know.

Thanks again for the great service!

--Ed Gifford

**Comment by egifford** [comment]
Some more information:

A query to http://wpackagist lists versions 1.0.3 and 1.0.4 as available:
http://wpackagist.org/search?q=custom-post-type-ui

A query through composer doesn't:
$ composer show wpackagist-plugin/custom-post-type-ui
name     : wpackagist-plugin/custom-post-type-ui
descrip. :
keywords :
versions : * dev-trunk, 1.0.2, 1.0.1, 1.0.0, 0.9.5, 0.9.0, 0.8.5, 0.8.4, 0.8.3, 0.8.2, 0.8.1, 0.8.0.0, 0.7.2.0, 0.7.1.0, 0.7.0.0, 0.6.2.0, 0.6.1.0, 0.6.0.0, 0.5.2.0, 0.5.1.0, 0.5.0.0, 0.4.1.0, 0.4.0
.0, 0.3.1.0, 0.3.0.0, 0.2.1.0, 0.2.0.0, 0.1.2.0, 0.1.1.0, 0.1.0.0
type     : wordpress-plugin
license  :
source   : [svn] http://plugins.svn.wordpress.org/custom-post-type-ui/ trunk
dist     : [zip] https://downloads.wordpress.org/plugin/custom-post-type-ui.zip
names    : wpackagist-plugin/custom-post-type-ui

**Comment by lavoiesl** [comment]
At first guess, I think it would be related to a cache issue.
Unfortunately, I can't look at it at the moment, can you try to gather more
info?

**Comment by tamlyn** [comment]
We had an issue with the build process. Since the server move it's been outputting the updated files to the wrong directory! Sorry about that, and thanks for taking the time to report the problem in detail.

**Comment by egifford** [comment]
Thanks for looking into this.

Everything is working great, now!
