### ISSUE TITLE
Unable to install wpackagist-plugin/ninja-forms 2.9.6

### ISSUE THREAD

**Issue by grappler** [outlandishideas/wpackagist#73]
I tried installing `wpackagist-plugin/ninja-forms:'*'` but I only got version `1.8.13`. If I define `"wpackagist-plugin/ninja-forms": "2.9.6"` then I get the following error
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package wpackagist-plugin/ninja-forms could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
```

I was able to install the rest of the plugins with an issue.

**Comment by Rarst** [comment]
Seems to be wpackagist issue with 2.9+ versions unavailable for some reason:

```
>composer show wpackagist-plugin/ninja-forms
name     : wpackagist-plugin/ninja-forms
descrip. :
keywords :
versions : dev-trunk, 2.8.13, 2.8.12...
```

**Comment by Giuseppe-Mazzapica** [comment]
Doing a [site search](http://wpackagist.org/search?q=ninja-forms&type=any) 2.9.6 is there. Weird.

**Comment by tamlyn** [comment]
We had an issue with the build process. Since the server move it's been outputting the updated files to the wrong directory! Sorry about that, and thanks for taking the time to report the problem.
