### ISSUE TITLE
getting  The requested package wpackagist-theme could not be found 

### ISSUE THREAD

**Issue by patforg** [outlandishideas/wpackagist#74]
Getting the following  error on composer update / install:

The requested package wpackagist-theme/devdmbootstrap3 could not be found in any version, there may be a typo in the package name.

The theme is in wpackagist:
http://wpackagist.org/search?q=devdmboot&type=theme&search=#

It has versions in svn https://themes.svn.wordpress.org/devdmbootstrap3/

Tried the following definitions:
"wpackagist-theme/devdmbootstrap3": "*",
"wpackagist-theme/devdmbootstrap3": "1.50",
"wpackagist-theme/devdmbootstrap3": "*@dev",
"wpackagist-theme/devdmbootstrap3": "dev-master",

Keep getting the error

**Comment by tamlyn** [comment]
Sorry about this. It's a known issue, see #68. It will be fixed but we do this in our spare time and things are busy at the moment. Any help appreciated!

**Comment by patforg** [comment]
Ok no worries, really appreciate your respnse.
