### ISSUE TITLE
Some themes marked as not active

### ISSUE THREAD

**Issue by dlecomte** [outlandishideas/wpackagist#75]
Hello,

Some themes are marked as not active whereas they exist on wordpress.org.

Samples : 
- hueman : http://wpackagist.org/search?q=hueman&type=theme&search=
https://wordpress.org/themes/hueman/

- onetone : http://wpackagist.org/search?q=onetone&type=theme&search=
https://wordpress.org/themes/onetone/

It is not possible to retreive them through composer. Do you know what is the matter ?

Best regards

**Comment by tamlyn** [comment]
Yes, this is a know issue, see #68. Thanks for reporting but closing as duplicate.
