### ISSUE TITLE
Genesis Widgetized Footer isn't in the package repository

### ISSUE THREAD

**Issue by neoncube2** [outlandishideas/wpackagist#76]
I'm new at this, so my apologies if this isn't a bug, but I was looking for [Genesis Widgetized Footer](https://wordpress.org/plugins/genesis-widgetized-footer/) and couldn't find it. Should it be listed?

**Comment by tamlyn** [comment]
I can see it here http://wpackagist.org/search?q=genesis-widgetized-footer 

You currently have to search for the hyphenated "slug" version of the plugin name, spaces won't work. Admittedly that's not clear and should be fixed. Was that your issue?

**Comment by neoncube2** [comment]
Ah, thank you :)
