### ISSUE TITLE
Login-Lockdown

### ISSUE THREAD

**Issue by r34ch** [outlandishideas/wpackagist#77]
Using composer update with

    "wpackagist-plugin/login-lockdown": "v1.6.1"

I get

    [RuntimeException]                                      
    Package could not be downloaded, sh: 1: svn: not foun

Clicking the link

    https://downloads.wordpress.org/plugin/login-lockdown.v1.6.1.zip

Gives a 404 file not found

    http://wpackagist.org/search?q=login-lockdown&type=any&search=

Seems available on WP plugins

    https://wordpress.org/plugins/login-lockdown/

**Comment by Rarst** [comment]
Link to 1.6.1 at https://wordpress.org/plugins/login-lockdown/developers/ is the same and gives 404 indeed, so issue seems to be on wp org side.

**Comment by lavoiesl** [comment]
As a workaround, you can install SVN.
