### ISSUE TITLE
lovecraft theme reporting as inactive with no versions

### ISSUE THREAD

**Issue by richardtape** [outlandishideas/wpackagist#78]
Anders Noren's [Lovecraft](http://www.andersnoren.se/teman/lovecraft-wordpress-theme/) theme is [available](https://wordpress.org/themes/lovecraft/) on the wp.org theme's repo at [https://themes.svn.wordpress.org/lovecraft/](https://themes.svn.wordpress.org/lovecraft/) but is being reported as "No version available." and inactive when searching [http://wpackagist.org/search?q=lovecraft&type=theme&search=](http://wpackagist.org/search?q=lovecraft&type=theme&search=)

Currently the theme is at version [1.13](https://themes.svn.wordpress.org/lovecraft/1.13/)

(as an aside, I just want to say thank you so, so much for providing this service. It is truly brilliant and adds so much value to the WordPress community. :ok_hand: )

**Comment by tamlyn** [comment]
This is now fixed. See #68 for details.
