### ISSUE TITLE
WP-optimize could not be found in any version

### ISSUE THREAD

**Issue by rzamana** [outlandishideas/wpackagist#82]
There is an odd behavior about this plugin.

I have two environments (DEV and PRE), the PRE environment is my server, and the DEV is our development machines.

So, on DEV the composer installs this plugin normally, but on PRE, I get this:
> Loading composer repositories with package information
> Installing dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - The requested package wpackagist-plugin/wp-optimize could not be found in any version, there may be a typo in the package name.
> 
> Potential causes:
>  - A typo in the package name
>  - The package is not available in a stable-enough version according to your minimum-stability setting
>    see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
> 
> Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by lavoiesl** [comment]
could you provide relevant parts of your `composer.json` and the output of `composer update -vvv`?

**Comment by rzamana** [comment]
Showing only the PRE environment.

## composer.json
>     "repositories": [
>         {
>             "type": "composer",
>             "url": "http://wpackagist.org"
>         },
>         {
>             "type": "package",
>             "package": {
>                 "name": "wordpress/wordpress",
>                 "version": "4.1.1",
>                 "type": "webroot",
>                 "dist": {
>                     "type": "zip",
>                     "url": "https://wordpress.org/wordpress-4.1.1.zip"
>                 },
>                 "require": {
>                     "fancyguy/webroot-installer": "1.1.0"
>                 }
>             }
>         }
>     ],
>     "require": {
>         "php": ">=5.3.0",
>         "wordpress/wordpress": "4.1.1",
>         "fancyguy/webroot-installer": "1.1.0",
>         "composer/installers": "v1.0.12",
>         "vlucas/phpdotenv": "1.0.9",
>         "wpackagist-plugin/contact-form-7": "*",
>         "wpackagist-plugin/google-sitemap-generator": "*",
>         "wpackagist-plugin/google-analytics-for-wordpress": "*",
>         "wpackagist-plugin/mobble": "*",
>         "wpackagist-plugin/multiple-post-thumbnails": "*",
>         "wpackagist-plugin/regenerate-thumbnails": "*",
>         "wpackagist-plugin/simple-image-widget": "*",
>         "wpackagist-plugin/wpmandrill": "*",
>         "wpackagist-plugin/wp-migrate-db": "*",
>         "wpackagist-plugin/wp-optimize": "*",
>         "wpackagist-plugin/wordpress-seo": "*"
>     },

## composer update -vvv
> Reading ./composer.json
> Loading config file ./composer.json
> Executing command (CWD): git describe --exact-match --tags
> Executing command (CWD): git branch --no-color --no-abbrev -v
> Executing command (CWD): hg branch
> Executing command (CWD): svn info --xml
> Failed to initialize global composer: Composer could not find the config file: /home/studioboz/.composer/composer.json
> To initialize a project, please create a composer.json file as described in the http://getcomposer.org/ "Getting Started" section
> Loading composer repositories with package information
> Downloading http://wpackagist.org/packages.json
> Writing /home/studioboz/.composer/cache/repo/http---wpackagist.org/packages.json into cache
> Downloading https://packagist.org/packages.json
> Writing /home/studioboz/.composer/cache/repo/https---packagist.org/packages.json into cache
> Updating dependencies (including require-dev)
> Downloading http://wpackagist.org/p/providers-2015-03$b7f878afba77b33260c8db3a8ff8b9531d61353cb268f67857b5522c80198105.json
> Writing /home/studioboz/.composer/cache/repo/http---wpackagist.org/p-providers-2015-03.json into cache
> Downloading http://wpackagist.org/p/providers-2013$bae857d27ebf5195a61485cb99d66f764e0428bb49dca69405c17c5053257075.json
> Writing /home/studioboz/.composer/cache/repo/http---wpackagist.org/p-providers-2013.json into cache
> Downloading http://wpackagist.org/p/providers-2012$f1258f21eca6e089ff4db4f8b64b68e578539a0382f647271a53826f8cc2b426.json
> Writing /home/studioboz/.composer/cache/repo/http---wpackagist.org/p-providers-2012.json into cache
> Downloading http://wpackagist.org/p/providers-old$6cdc4c5f8aba322068b0ba0ba99db82dfc0e22aeff186acdf69b597eba4001f7.json
> Writing /home/studioboz/.composer/cache/repo/http---wpackagist.org/p-providers-old.json into cache
> Downloading http://wpackagist.org/p/providers-2011$c3021874dc3f3aa47be0a2cda586e90156c00de6db11ff1422df73392132b0a1.json
> Writing /home/studioboz/.composer/cache/repo/http---wpackagist.org/p-providers-2011.json into cache
> Downloading http://wpackagist.org/p/providers-2014$ef7340a2a831d7235bf46369fb479758a5fc8063bdfb3680032aa0d734776078.json
> Writing /home/studioboz/.composer/cache/repo/http---wpackagist.org/p-providers-2014.json into cache
> Downloading http://wpackagist.org/p/providers-this-week$5a0b8ba452039686c38f737ffb8d40987a5c7976b650b6b9adac3488b52f6220.json
> Writing /home/studioboz/.composer/cache/repo/http---wpackagist.org/p-providers-this-week.json into cache
> Downloading https://packagist.org/p/provider-2013$da4cac940612024a2f5a0e571c3b9a5f94e4f06e0278fac44aa0b9c13582b3b8.json
> Writing /home/studioboz/.composer/cache/repo/https---packagist.org/p-provider-2013.json into cache
> Downloading https://packagist.org/p/provider-2014$80180f98a4cccbdf29e52b4f6cffa1a56823bea9c704d3548905d8995e8c00ac.json
> Writing /home/studioboz/.composer/cache/repo/https---packagist.org/p-provider-2014.json into cache
> Downloading https://packagist.org/p/provider-2014-04$1f71ecf6f13656f88666f4bc7762ebd6d7877d0e9a2d7dad7d75104de4bca3e8.json
> Writing /home/studioboz/.composer/cache/repo/https---packagist.org/p-provider-2014-04.json into cache
> Downloading https://packagist.org/p/provider-2014-07$118e542df7aaf9bbf12154b7d33a77edb35a44331452f0ab09c1b1936322db6d.json
> Writing /home/studioboz/.composer/cache/repo/https---packagist.org/p-provider-2014-07.json into cache
> Downloading https://packagist.org/p/provider-2014-10$d63d539a31820b76c04727cfa3bb06ab8af63d1c93871ce0f11d45bdce77b886.json
> Writing /home/studioboz/.composer/cache/repo/https---packagist.org/p-provider-2014-10.json into cache
> Downloading https://packagist.org/p/provider-2015-01$a6e5af3cb738a5bef88b146be6c0a66b4013541df8a1cb61f84d0dba0a55b39c.json
> Writing /home/studioboz/.composer/cache/repo/https---packagist.org/p-provider-2015-01.json into cache
> Downloading https://packagist.org/p/provider-archived$b0b657c066ee8cf6df223e501fd06b17baaa04a363386e86c82cf001e3e5a238.json
> Writing /home/studioboz/.composer/cache/repo/https---packagist.org/p-provider-archived.json into cache
> Downloading https://packagist.org/p/provider-latest$fb1c710cd1159efd09c8a2ef739ef39a471b9f6992ee3e79acc3030f0582206c.json
> Writing /home/studioboz/.composer/cache/repo/https---packagist.org/p-provider-latest.json into cache
> Reading /home/studioboz/.composer/cache/repo/https---packagist.org/provider-fancyguy$webroot-installer.json from cache
> Reading /home/studioboz/.composer/cache/repo/https---packagist.org/provider-composer$installers.json from cache
> Reading /home/studioboz/.composer/cache/repo/https---packagist.org/provider-vlucas$phpdotenv.json from cache
> Downloading http://wpackagist.org/p/wpackagist-plugin/mobble$89585e485c3ddede6122be045bdb40c816272069f359bf6ac2bbb2745170d633.json
> Writing /home/studioboz/.composer/cache/repo/http---wpackagist.org/provider-wpackagist-plugin$mobble.json into cache
> Downloading http://wpackagist.org/p/wpackagist-plugin/contact-form-7$197ca6ae5083af679ba08d26bf38a92101d93e16e47130310caaa263910e9a36.json
> Writing /home/studioboz/.composer/cache/repo/http---wpackagist.org/provider-wpackagist-plugin$contact-form-7.json into cache
> Downloading http://wpackagist.org/p/wpackagist-plugin/google-sitemap-generator$dbb11aa7e7c14f16bf0d16c5a9a6a9f9d5c7cfc5ea8886436401236ff9b2ead8.json
> Writing /home/studioboz/.composer/cache/repo/http---wpackagist.org/provider-wpackagist-plugin$google-sitemap-generator.json into cache
> Downloading http://wpackagist.org/p/wpackagist-plugin/google-analytics-for-wordpress$eeaa140da60d4cf4934b8e68df8f0df16bdbb9460c64f45a18e7be096adb8232.json
> Writing /home/studioboz/.composer/cache/repo/http---wpackagist.org/provider-wpackagist-plugin$google-analytics-for-wordpress.json into cache
> Downloading http://wpackagist.org/p/wpackagist-plugin/multiple-post-thumbnails$2531e3c95e379b98910a97cabe7afe51d5c702cca1fe06be0c2e8cf13f119e2a.json
> Writing /home/studioboz/.composer/cache/repo/http---wpackagist.org/provider-wpackagist-plugin$multiple-post-thumbnails.json into cache
> Downloading http://wpackagist.org/p/wpackagist-plugin/regenerate-thumbnails$5882f0d298ff556b9615a3355c9f7731a199d6b42a891cd8b1f1c3cb37acf28b.json
> Writing /home/studioboz/.composer/cache/repo/http---wpackagist.org/provider-wpackagist-plugin$regenerate-thumbnails.json into cache
> Downloading http://wpackagist.org/p/wpackagist-plugin/simple-image-widget$9056597ec2f9988d3692b01cfb80cacd3bf38a9dc1dcbccab50b7373a49dc09e.json
> Writing /home/studioboz/.composer/cache/repo/http---wpackagist.org/provider-wpackagist-plugin$simple-image-widget.json into cache
> Downloading http://wpackagist.org/p/wpackagist-plugin/wpmandrill$b2c01db95c2ddd59f8dba212c77114082e1bf9322fc4aff950b56da2d3a4a6dc.json
> Writing /home/studioboz/.composer/cache/repo/http---wpackagist.org/provider-wpackagist-plugin$wpmandrill.json into cache
> Downloading http://wpackagist.org/p/wpackagist-plugin/wp-migrate-db$0b9c70c325704fb3b04f404e2125f0c3040db3bdb16d81307e48c5fc80b7001f.json
> Writing /home/studioboz/.composer/cache/repo/http---wpackagist.org/provider-wpackagist-plugin$wp-migrate-db.json into cache
> Downloading http://wpackagist.org/p/wpackagist-plugin/wordpress-seo$aaa019add046f399b43bbdf6db93a42295175d432391b5547d3d79922b736451.json
> Writing /home/studioboz/.composer/cache/repo/http---wpackagist.org/provider-wpackagist-plugin$wordpress-seo.json into cache
> Reading /home/studioboz/.composer/cache/repo/https---packagist.org/provider-shama$baton.json from cache
> Your requirements could not be resolved to an installable set of packages.
> 
> Problem 1
>     - The requested package wpackagist-plugin/wp-optimize could not be found in any version, there may be a typo in the package name.
> 
> Potential causes:
>     - A typo in the package name
>     - The package is not available in a stable-enough version according to your minimum-stability setting
>     see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
> 
> Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
>

**Comment by tamlyn** [comment]
See #145
