### ISSUE TITLE
gotmls could not be found in any version

### ISSUE THREAD

**Issue by rapind** [outlandishideas/wpackagist#84]
Looks like it's there according to the site http://wpackagist.org/search?q=gotmls but I get this error regardless of version (even with *).

"The requested package wpackagist-plugin/gotmls could not be found in any version, there may be a typo in the package name."

Seeing the same issue for "wpackagist-plugin/wp-password-policy-manager".

**Comment by rapind** [comment]
Relevant composer.json entries:

      "wpackagist-plugin/gotmls": "*",
      "wpackagist-plugin/wp-password-policy-manager": "*"

**Comment by tamlyn** [comment]
See #145
