### ISSUE TITLE
wp-password-policy-manager could not be found in any version

### ISSUE THREAD

**Issue by rapind** [outlandishideas/wpackagist#85]
Looks like it's there according to the site http://wpackagist.org/search?q=wp-password-policy-manager but I get this error regardless of version (even with *).

"The requested package wpackagist-plugin/wp-password-policy-manager could not be found in any version, there may be a typo in the package name."

**Comment by lavoiesl** [comment]
Most probably a duplicate of #84

**Comment by rapind** [comment]
Yes sorry, it is probably the same root cause, but I reported it separately because it might require an additional action (updating of files).

**Comment by lavoiesl** [comment]
Let’s close this one in favour of the other and reopen if needed.
