### ISSUE TITLE
wpackagist-plugin/sb-rss-feed-plus

### ISSUE THREAD

**Issue by jfortier** [outlandishideas/wpackagist#89]
In my composer.json

     //..packages..
     "wpackagist-plugin/sb-rss-feed-plus": "1.4.12"

Via command line:

     $ composer show wpackagist-plugin/sb-rss-feed-plus
        [InvalidArgumentException]
        Package wpackagist-plugin/sb-rss-feed-plus not found

Meanwhile, it's marked active and at the latest version:
http://wpackagist.org/search?q=sb-rss-feed-plus&type=any&search=

I literally copied and pasted the string from your site. Let me know if I should run anything to help debug this issue.

Plugin also still available on WP site:
https://wordpress.org/plugins/sb-rss-feed-plus/

Composer version 1.0-dev (4d5d5247045f2875cc6516d061641459a2108e3b) 2015-05-07 15:28:18

**Comment by tamlyn** [comment]
Seems to be working now. Are you still experiencing problems?

**Comment by jfortier** [comment]
@tamlyn Off and on it seems, which is breaking my deploys. This worked for a little bit, and seems to be broken again. Also running into an issue with "wpackagist-plugin/wp-mail-bank" : "1.20"

Is there anything I can do to help debug this? I've cleared my composer cache as well after receiving these errors, as well as upgraded my composer version. No difference.

**Comment by tamlyn** [comment]
See #145
