### ISSUE TITLE
Add installer for languages

### ISSUE THREAD

**Issue by hason** [outlandishideas/wpackagist#91]
https://codex.wordpress.org/Installing_WordPress_in_Your_Language

**Comment by Rarst** [comment]
wpackagist doesn't handle WP core in first place? Though managing WP language stuff with Composer is definitely one of lingering issues.

**Comment by tamlyn** [comment]
Closing this as needs more info. Please reopen if desired.

**Comment by NoelLH** [comment]
I'm going to close this as a dupe of the newer #121 as there is more detailed discussion and alternatives we might take inspiration from on that issue.
