### ISSUE TITLE
JSON API

### ISSUE THREAD

**Issue by reiz** [outlandishideas/wpackagist#92]
This project is awesome. I would like to build an integration for [VersionEye](https://www.VersionEye.com). Some of my users really would like to [see that integration](https://bitbucket.org/versioneye/versioneye/issue/60/composer-packages-from-wpackagist-not) and it makes a lot of sense. Does [wpackagist](http://wpackagist.org) has an JSON API? Or an Satis interface?

**Comment by Rarst** [comment]
Isn't Composer repository format inherently a JSON API of sorts?.. :)

**Comment by reiz** [comment]
Just found it :-)

**Comment by tamlyn** [comment]
Also bear in mind that you can download the project and run it locally. Then you can query the local SQLite database that it creates however you like.
