### ISSUE TITLE
wpackagist-plugin/yet-another-related-posts-plugin could not be found in any version

### ISSUE THREAD

**Issue by iequalszero** [outlandishideas/wpackagist#93]
I can see it in the WP Plugins repo, and it's been recently updated. WPackagist says it's not active.

**Comment by TheCognito** [comment]
+1 to this issue

**Comment by ozthegreat** [comment]
+1

**Comment by tamlyn** [comment]
I've manually reactivated this. 

Some packages occasionally get incorrectly marked as inactive. It's a pain but we haven't had a chance to track down why it happens yet. Any help appreciated.
