### ISSUE TITLE
ninja-forms and advanced-custom-fields could not be found in any version

### ISSUE THREAD

**Issue by Poggen** [outlandishideas/wpackagist#94]
Problem 1
    - The requested package wpackagist/advanced-custom-fields could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package wpackagist/ninja-forms could not be found in any version, there may be a typo in the package name.

http://plugins.svn.wordpress.org/ninja-forms/
http://plugins.svn.wordpress.org/advanced-custom-fields/

**Comment by tamlyn** [comment]
The following works for me. If you're still having problems please post the contents of your  `composer.json`.

```
{
    "repositories":[
        {
            "type":"composer",
            "url":"http://wpackagist.org"
        }
    ],
    "require": {
        "wpackagist-plugin/ninja-forms": "*",
        "wpackagist-plugin/advanced-custom-fields":"*"
    }
}
```
