### ISSUE TITLE
Error 404 for "wpackagist-plugin/woocommerce-de": "3.2.0"

### ISSUE THREAD

**Issue by jscontrust** [outlandishideas/wpackagist#95]
Installing "wpackagist-plugin/woocommerce-de": "3.2.0" with composer causes:

  - Installing wpackagist-plugin/woocommerce-de (3.2.0)
    Downloading: Connecting...    Failed to download wpackagist-plugin/woocommerce-de from dist: The "http://downloads.wordpress.org/plugin/woocommerce-de.3.2.0.zip" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing wpackagist-plugin/woocommerce-de (3.2.0)
    Checking out tags/3.2.0

**Comment by tamlyn** [comment]
Looks like that plugin doesn't exist: https://wordpress.org/plugins/woocommerce-de/

Perhaps you were looking for this https://wordpress.org/plugins/woocommerce-germanized/

**Comment by jscontrust** [comment]
It was a plugin from http://deckerweb.de/ and avaiable in Version 3.2.0 from wpackagist some weeks ago. 

http://wpackagist.org/search?q=woocommerce-de&type=any&search=

**Comment by tamlyn** [comment]
Yes, I can see it [in the repo](http://plugins.svn.wordpress.org/woocommerce-de/trunk/) so perhaps it's been deleted? Seems odd.
