### ISSUE TITLE
Yet Another Related Posts Plugin not at current version

### ISSUE THREAD

**Issue by jasonbutler42** [outlandishideas/wpackagist#97]
Trying to update YARPP to 4.2.5 (https://wordpress.org/plugins/yet-another-related-posts-plugin/). 

This is in my composer.json:
> "wpackagist-plugin/yet-another-related-posts-plugin": "4.2.5"

When I run composer update, I get this response:
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>    - The requested package wpackagist-plugin/yet-another-related-posts-plugin could not be found in any version, there may be a typo in the package name.

> Potential causes:
> - A typo in the package name
> - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
>
> Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

When I search wpackagist, I find that the plugin is at 4.2.4 (http://wpackagist.org/search?q=yet-another-related-posts-plugin&type=plugin&search=#).

**Comment by jfortier** [comment]
Yeah, I'm receiving this error with several plugins as well. Would really like to know what the cause is, or if there's any known workarounds. This is preventing from deploying at times, which is not good. Anyone got any clues here?

**Comment by mattics** [comment]
I am also receiving this error when trying to update Yet Another Related Posts Plugin to 4.2.5 and have been for the past couple of months.

There is a tag for 4.2.5 (http://plugins.svn.wordpress.org/yet-another-related-posts-plugin/tags/)

4.2.4 works as expected so I have just been sticking to this version for now when doing updates to client sites.

**Comment by FreshFlesh** [comment]
4.2.5 is clearly missing from wpackagist : http://wpackagist.org/search?q=yet-another-related

**Comment by xavivars** [comment]
I'm also looking for this plugin

**Comment by tamlyn** [comment]
See #145
