### ISSUE TITLE
Unable to find "Posts 2 Posts"

### ISSUE THREAD

**Issue by joakimcarlsten** [outlandishideas/wpackagist#99]
Hi,
I haven't been able to find the posts 2 posts plugin on the wpackagist even though it is visible on wordpress.org. Is there something I'm not getting?

Thanks in advance

**Comment by tamlyn** [comment]
Works for me:

    $ composer require wpackagist-plugin/posts-to-posts
    Using version ^1.6 for wpackagist-plugin/posts-to-posts
    ./composer.json has been updated
    Loading composer repositories with package information
    Updating dependencies (including require-dev)
      - Installing composer/installers (v1.0.21)
        Downloading: 100%

      - Installing wpackagist-plugin/posts-to-posts (1.6.4)
        Downloading: 100%
    
    Writing lock file
    Generating autoload files

Please post your `composer.json` if you're still having problems.

**Comment by joakimcarlsten** [comment]
Hi sorry, My bad.

It wasn't working before, but now it worked. I might have been leaving out the new "-plugin" to wpackagist. Thanks for the help.
